import type { RadarEntrySeed } from "./release-radar.ts";

export const radarExpansionSeeds: RadarEntrySeed[] = [
  {
    kind: "event",
    slug: "cary-beer-bourbon-bbq-2026",
    eyebrow: "North Carolina event",
    title: "Cary's Beer, Bourbon & BBQ Festival returns for two days",
    dek: "Two separately timed sessions bring bourbon sampling, food, and live music to Koka Booth Amphitheatre.",
    summary: "The official organizer lists Cary's 2026 Beer, Bourbon & BBQ Festival for July 31 and August 1. Admission includes sampling, but ticket tier, entry time, and venue rules differ by session.",
    startDate: "2026-07-31",
    endDate: "2026-08-01",
    occurrences: [
      { date: "2026-07-31", label: "Friday · 6–10 PM", schemaStartDate: "2026-07-31T18:00:00-04:00", schemaEndDate: "2026-07-31T22:00:00-04:00" },
      { date: "2026-08-01", label: "Saturday · 12–6 PM", schemaStartDate: "2026-08-01T12:00:00-04:00", schemaEndDate: "2026-08-01T18:00:00-04:00" },
    ],
    dateLabel: "Jul 31 & Aug 1",
    status: "upcoming",
    states: ["North Carolina"],
    location: "Koka Booth Amphitheatre · Cary, North Carolina",
    availability: "Ticketed bourbon festival",
    calendar: true,
    featured: true,
    updatedAt: "2026-07-21",
    facts: [
      { label: "Friday", value: "July 31 · 6–10 PM" },
      { label: "Saturday", value: "August 1 · VIP noon, GA 2 PM" },
      { label: "Format", value: "Beer and bourbon sampling" },
      { label: "Action", value: "Check ticket tier and venue policy" },
    ],
    sections: [
      { heading: "What is confirmed", body: "The organizer publishes two 2026 dates with separate Friday and Saturday admission windows at Koka Booth Amphitheatre." },
      { heading: "Why it is useful", body: "The event offers a broad tasting opportunity rather than a scarce-bottle purchase promise. The fixed schedule makes ticket and travel planning actionable." },
      { heading: "Before attending", body: "Confirm ticket inclusions, designated-driver access, clear-bag rules, age requirements, and the current pour list directly with the organizer." },
    ],
    sources: [{ label: "Cary Beer, Bourbon & BBQ Festival", url: "https://cary.beerandbourbon.com/", type: "official" }],
  },
  {
    kind: "event",
    slug: "north-carolina-bourbon-spirits-festival-2026",
    eyebrow: "North Carolina event",
    title: "NC Bourbon & Spirits Festival sets a September date",
    dek: "North Carolina spirits tastings and a full concert bill share one ticket at Carolina Crossroads.",
    summary: "Visit Halifax lists the NC Bourbon & Spirits Festival for September 12, 2026, from 3:00 to 11:30 p.m. The separate tasting area is restricted to guests 21 and older with valid identification.",
    startDate: "2026-09-12",
    schemaStartDate: "2026-09-12T15:00:00-04:00",
    schemaEndDate: "2026-09-12T23:30:00-04:00",
    dateLabel: "Sep 12, 2026",
    status: "upcoming",
    states: ["North Carolina"],
    location: "Carolina Crossroads Amphitheatre · Roanoke Rapids, North Carolina",
    availability: "Ticketed festival; tasting area is 21+",
    calendar: true,
    updatedAt: "2026-07-21",
    facts: [
      { label: "Date", value: "September 12 · 3–11:30 PM" },
      { label: "Location", value: "Roanoke Rapids" },
      { label: "Tasting", value: "Separate 21+ spirits area" },
      { label: "Action", value: "Review admission and ID rules" },
    ],
    sections: [
      { heading: "What is confirmed", body: "The destination's official event listing publishes the date, hours, venue, concert lineup, and a North Carolina bourbon and spirits tasting component." },
      { heading: "Access context", body: "The festival is open to all ages, but entry to the included spirits-tasting area requires a valid photo ID and age 21 or older." },
      { heading: "Bottle context", body: "A tasting festival does not establish take-home bottle inventory. Use producer and retailer sources for any purchase opportunity announced around the event." },
    ],
    sources: [{ label: "Visit Halifax event listing", url: "https://www.visithalifax.com/event/nWGT/nc-bourbon-spirits-festival", type: "official" }],
  },
  {
    kind: "event",
    slug: "charlotte-whiskey-wine-fire-2026",
    eyebrow: "North Carolina event",
    title: "Charlotte Whiskey, Wine & Fire returns in October",
    dek: "An outdoor evening combines whiskey bars, wine, cocktails, live music, and fire-cooked food.",
    summary: "The official organizer schedules Charlotte Whiskey, Wine & Fire for October 24, 2026. VIP admission begins at 4:00 p.m. and general admission begins at 5:00 p.m.",
    startDate: "2026-10-24",
    schemaStartDate: "2026-10-24T16:00:00-04:00",
    schemaEndDate: "2026-10-24T21:00:00-04:00",
    dateLabel: "Oct 24, 2026",
    status: "upcoming",
    states: ["North Carolina"],
    location: "Charlotte, North Carolina",
    availability: "Ticketed outdoor tasting event",
    calendar: true,
    updatedAt: "2026-07-21",
    facts: [
      { label: "Date", value: "October 24 · 4–9 PM" },
      { label: "VIP", value: "Entry begins at 4 PM" },
      { label: "General", value: "Entry begins at 5 PM" },
      { label: "Requirement", value: "21+ to sample alcohol" },
    ],
    sections: [
      { heading: "What is confirmed", body: "The organizer publishes the October date, separate admission windows, and a program built around whiskey, wine, cocktails, food, and live music." },
      { heading: "Planning context", body: "This is an outdoor event. Review ticket inclusions, weather policy, transportation, and age requirements before booking." },
      { heading: "Release context", body: "Brand pours can help discovery, but an event pour is not a claim that a limited bottle is available for retail purchase." },
    ],
    sources: [{ label: "Charlotte Whiskey, Wine & Fire", url: "https://charlotte.whiskeywinefire.com/", type: "official" }],
  },
  {
    kind: "event",
    slug: "greensboro-abc-hickory-branch-bourbon-tasting-2026",
    eyebrow: "North Carolina ABC store event",
    title: "Greensboro ABC schedules a Hickory Branch bourbon tasting",
    dek: "A distillery representative will pour Sergeant's Valor Select Bourbon at one exact Greensboro store and time.",
    summary: "Greensboro ABC lists a July 24 tasting from 3:00 to 6:00 p.m. at its Hickory Branch store. Guests must be 21 or older and present valid identification to sample.",
    startDate: "2026-07-24",
    schemaStartDate: "2026-07-24T15:00:00-04:00",
    schemaEndDate: "2026-07-24T18:00:00-04:00",
    dateLabel: "Jul 24 · 3–6 PM",
    status: "upcoming",
    states: ["North Carolina"],
    location: "ABC Store – Hickory Branch · 500 Hickory Branch Rd, Greensboro, NC",
    availability: "Free in-store tasting for eligible guests",
    calendar: true,
    updatedAt: "2026-07-21",
    facts: [
      { label: "Date", value: "July 24 · 3–6 PM" },
      { label: "Store", value: "Hickory Branch" },
      { label: "Bourbon", value: "Sergeant's Valor Select" },
      { label: "Requirement", value: "21+ with valid ID" },
    ],
    sections: [
      { heading: "What is confirmed", body: "Greensboro ABC publishes the exact store, address, tasting hours, featured products, and age requirement for this event." },
      { heading: "What to expect", body: "A distillery representative is scheduled to offer samples of Sergeant's Valor Select Bourbon and Madam Col. Pistachio Bourbon Cream." },
      { heading: "Bottle context", body: "A tasting announcement does not promise take-home inventory or a purchase opportunity. Check the store directly for current retail availability." },
    ],
    sources: [{ label: "Greensboro ABC Hickory Branch tasting", url: "https://www.greensboroabc.com/events/hickory-branch-tasting-july-24-2026/", type: "state" }],
  },
  {
    kind: "lottery",
    slug: "durham-abc-annual-bourbon-lottery-2026-watch",
    eyebrow: "North Carolina lottery watch",
    title: "Durham ABC's annual bourbon lottery moves onto the fall watchlist",
    dek: "Durham confirms a once-yearly local lottery, but the 2026 entry window is not open yet.",
    summary: "Durham ABC says its annual lottery runs during the fall and winter and that entries are not currently open. The board's official bourbon page—not an estimated date—will control when the next application window is announced.",
    startDate: "2026-09",
    dateLabel: "Fall–winter 2026 watch",
    status: "watch",
    states: ["North Carolina"],
    location: "Durham County, North Carolina",
    availability: "Entry window not yet open",
    updatedAt: "2026-07-21",
    facts: [
      { label: "Program", value: "Annual rare-bourbon lottery" },
      { label: "Current state", value: "Entries not open" },
      { label: "Broad timing", value: "Fall and winter" },
      { label: "Action", value: "Recheck Durham's official bourbon page" },
    ],
    sections: [
      { heading: "What is confirmed", body: "Durham ABC's official bourbon page identifies an annual rare-bourbon lottery alongside weekly allocated drops and special release events." },
      { heading: "What is not confirmed", body: "No exact 2026 opening date, closing date, bottle list, or drawing date is published on the reviewed page. This record therefore stays outside exact calendar cells." },
      { heading: "How to prepare", body: "Read the current eligibility, entry, contact, and pickup rules when the form opens; prior-cycle rules are not a substitute for the next official notice." },
    ],
    sources: [{ label: "Durham ABC bourbon programs", url: "https://www.durhamabc.com/bourbon", type: "state" }],
  },
  {
    kind: "lottery",
    slug: "mecklenburg-abc-specialty-lottery-barrelpalooza-2026-watch",
    eyebrow: "North Carolina lottery watch",
    title: "Mecklenburg's specialty lottery and Barrelpalooza remain on watch",
    dek: "Mecklenburg confirms both standing release channels while withholding an unsupported next-event date.",
    summary: "Mecklenburg County ABC says it holds lotteries for allocated bourbon and operates Barrelpalooza as a limited-release event. The reviewed official page does not publish a future 2026 date, so this is a program watch rather than a calendar event.",
    startDate: "2026",
    dateLabel: "2026 schedule watch",
    status: "watch",
    states: ["North Carolina"],
    location: "Charlotte and Mecklenburg County, North Carolina",
    availability: "Future date not yet published",
    updatedAt: "2026-07-21",
    facts: [
      { label: "Channels", value: "Specialty lottery and Barrelpalooza" },
      { label: "Lottery", value: "Allocated bourbon purchase opportunity" },
      { label: "Event", value: "Limited-release products and barrel picks" },
      { label: "Action", value: "Join the official Spirited Mailing List" },
    ],
    sections: [
      { heading: "What is confirmed", body: "Mecklenburg publishes a standing specialty-products lottery program and describes Barrelpalooza as its signature limited-release event." },
      { heading: "What is not confirmed", body: "The reviewed page does not state the next 2026 lottery or Barrelpalooza date. Prior interviews and earlier events are not a substitute for a current notice." },
      { heading: "How entry can work", body: "Mecklenburg notes that event administration may include an on-site drawing with priority entry. The current event rules control if and when that format is used." },
    ],
    sources: [{ label: "Mecklenburg specialty lottery and Barrelpalooza", url: "https://www.meckabc.com/store_operations/specialty_products_lottery.php", type: "state" }],
  },
  {
    kind: "release",
    slug: "garrison-brothers-laguna-madre-2026",
    eyebrow: "Distillery release",
    title: "Garrison Brothers sets an August release for Laguna Madre",
    dek: "The eight-year Texas bourbon returns with an exact distillery release date in Hye.",
    summary: "Garrison Brothers lists its 2026 Laguna Madre release party at the Hye distillery for August 8. The 101-proof bourbon spends four years in American oak and four more in French Limousin oak.",
    startDate: "2026-08-08",
    schemaStartDate: "2026-08-08T08:00:00-05:00",
    schemaEndDate: "2026-08-08T16:00:00-05:00",
    dateLabel: "Aug 8, 2026",
    status: "upcoming",
    states: ["Texas"],
    location: "Garrison Brothers Distillery · Hye, Texas",
    bottle: "Garrison Brothers Laguna Madre 2026",
    msrp: "$349.99",
    proof: "101 proof",
    availability: "Distillery release event",
    calendar: true,
    featured: true,
    updatedAt: "2026-07-21",
    facts: [
      { label: "Distillery date", value: "August 8 · 8 AM–4 PM" },
      { label: "Age", value: "8 years" },
      { label: "Proof", value: "101" },
      { label: "Event price", value: "$349.99 standard · $409.99 cask strength" },
    ],
    sections: [
      { heading: "The release", body: "Laguna Madre combines extended Texas aging with maturation in American oak and French Limousin oak for one of Garrison Brothers' most limited annual releases." },
      { heading: "Exact event signal", body: "August 8 is the official Hye distillery release-party date. It does not establish a synchronized arrival date for outside retail markets." },
      { heading: "Before traveling", body: "Use Garrison Brothers' current event listing for arrival, purchase limits, age requirements, parking, and any event-specific rules. A calendar listing does not reserve a bottle." },
    ],
    sources: [
      { label: "Garrison Brothers 2026 Laguna Madre release", url: "https://www.garrisonbros.com/events/2026-laguna-madre-release/", type: "official" },
      { label: "Garrison Brothers Laguna Madre", url: "https://www.garrisonbros.com/our-babies/laguna-madre/", type: "official" },
    ],
  },
  {
    kind: "release",
    slug: "heaven-hill-bottled-in-bond-double-mash-2026",
    eyebrow: "August release watch",
    title: "Heaven Hill introduces a Bottled-in-Bond Double Mash bourbon",
    dek: "A first-of-its-kind production method joins Heaven Hill's national limited-release slate in August.",
    summary: "Heaven Hill says Bottled-in-Bond Double Mash will become available in limited quantities nationwide beginning August 2026. No exact national shelf date is promised.",
    startDate: "2026-08",
    dateLabel: "Beginning August 2026",
    status: "watch",
    states: ["Nationwide"],
    bottle: "Heaven Hill Bottled-in-Bond Double Mash",
    msrp: "$49.99",
    proof: "100 proof",
    availability: "Limited nationwide release",
    updatedAt: "2026-07-21",
    facts: [
      { label: "Window", value: "Beginning August 2026" },
      { label: "Age", value: "9 years" },
      { label: "Standard", value: "Bottled-in-Bond" },
      { label: "Proof", value: "100" },
      { label: "Suggested retail", value: "$49.99" },
    ],
    sections: [
      { heading: "What Double Mash means", body: "Heaven Hill describes a production approach that combines two separately mashed and distilled lots under the requirements of Bottled-in-Bond bourbon." },
      { heading: "Release timing", body: "The official source supports an August beginning, not one universal release day. Distribution can reach states and retailers at different times." },
      { heading: "Hunting context", body: "Treat the producer window as an early watch signal. A current state listing, retailer record, or sighting is needed before calling it locally available." },
    ],
    sources: [{ label: "Heaven Hill Double Mash announcement", url: "https://heavenhill.com/news-and-notes/heaven-hill-distillery-rewrites-bottled-in-bond-tradition-with-first-of-its-kind-double-mash-bourbon/", type: "official" }],
  },
  {
    kind: "release",
    slug: "yellowstone-limited-edition-port-casks-2026",
    eyebrow: "August release watch",
    title: "Yellowstone's 2026 Limited Edition marries two port finishes",
    dek: "Seven- and fourteen-year bourbons are finished separately in Ruby and Tawny Port casks before blending.",
    summary: "Yellowstone's 2026 Limited Edition is scheduled to reach select U.S. retailers beginning in August after an initial Limestone Branch visitor-center release. Market arrival remains allocation-dependent.",
    startDate: "2026-08",
    dateLabel: "Retail rollout begins August 2026",
    status: "watch",
    states: ["Kentucky", "Nationwide"],
    bottle: "Yellowstone 2026 Limited Edition",
    proof: "101 proof",
    availability: "Visitor center, then select U.S. retailers",
    updatedAt: "2026-07-21",
    facts: [
      { label: "Bourbons", value: "7 and 14 years" },
      { label: "Finishes", value: "Ruby and Tawny Port casks" },
      { label: "Proof", value: "101" },
      { label: "Retail window", value: "Beginning August" },
    ],
    sections: [
      { heading: "The blend", body: "Master Distiller Stephen Beam finished the two age groups separately in different styles of Port cask before marrying them for the final release." },
      { heading: "Release sequence", body: "The producer begins at Limestone Branch Distillery and then moves to select retail accounts. The August window does not identify a local arrival day." },
      { heading: "Availability context", body: "Limited national distribution can be uneven. Wait for a current state, retailer, or member source before treating the bottle as available nearby." },
    ],
    sources: [
      { label: "Yellowstone 2026 Limited Edition announcement", url: "https://www.prnewswire.com/news-releases/yellowstone-bourbon-unveils-2026-limited-edition-bourbon-finished-in-ruby-and-tawny-port-casks-302825541.html", type: "official" },
      { label: "Yellowstone Limited Edition", url: "https://yellowstonebourbon.com/limited-edition/", type: "official" },
    ],
  },
  {
    kind: "release",
    slug: "makers-mark-star-hill-farm-whisky-2026",
    eyebrow: "Producer release",
    title: "Maker's Mark returns Star Hill Farm Whisky with a new wheat study",
    dek: "The second annual estate-whiskey release shifts its grain focus while preserving the series' farm-to-flavor premise.",
    summary: "Maker's Mark and Suntory Global Spirits officially identify a 2026 Star Hill Farm Whisky release using new wheat varieties. The producer record supports a 2026 release watch, not a local inventory claim.",
    startDate: "2026",
    dateLabel: "2026 release",
    status: "watch",
    states: ["Kentucky", "Nationwide"],
    bottle: "Maker's Mark Star Hill Farm Whisky 2026",
    availability: "Limited annual release",
    updatedAt: "2026-07-21",
    facts: [
      { label: "Edition", value: "Second annual release" },
      { label: "Category", value: "American wheat whisky" },
      { label: "Focus", value: "Hard red and hard white wheat" },
      { label: "Certification", value: "Estate Whiskey Alliance" },
    ],
    sections: [
      { heading: "What changed", body: "The 2026 edition moves beyond the inaugural soft-red-winter-wheat study to explore hard red and hard white wheat varieties." },
      { heading: "Why it matters", body: "Star Hill Farm is Maker's Mark's first new mash bill in decades and is designed as an evolving annual study rather than a fixed core expression." },
      { heading: "Availability context", body: "Official product and corporate announcements establish the edition. Current retailer or state evidence is still necessary for a local purchase lead." },
    ],
    sources: [
      { label: "Maker's Mark Star Hill Farm Whisky", url: "https://www.makersmark.com/en-us/whisky/star-hill-farm-whisky", type: "official" },
      { label: "Suntory Global Spirits 2026 announcement", url: "https://www.suntoryglobalspirits.com/news/makers-mark-celebrates-flavor-nature-return-star-hill-farm-whisky-2026", type: "official" },
    ],
  },
  {
    kind: "release",
    slug: "russells-reserve-13-year-spring-2026",
    eyebrow: "Limited release watch",
    title: "Russell's Reserve 13 Year returns for Eddie Russell's 45th year",
    dek: "The spring 2026 barrel-proof release carries a commemorative label honoring Eddie Russell's distilling career.",
    summary: "Russell's Reserve officially identifies a Spring 2026 release of its 13 Year Old Bourbon. Availability is limited across online, visitor-center, and select-retailer channels.",
    startDate: "2026",
    dateLabel: "Spring 2026 release",
    status: "watch",
    states: ["Kentucky", "Nationwide"],
    bottle: "Russell's Reserve 13 Year Old Bourbon Spring 2026",
    msrp: "$200",
    availability: "Limited online, visitor-center, and retail release",
    updatedAt: "2026-07-21",
    facts: [
      { label: "Age", value: "13 years" },
      { label: "Edition", value: "Spring 2026" },
      { label: "Tribute", value: "Eddie Russell's 45th year" },
      { label: "Suggested retail", value: "$200" },
    ],
    sections: [
      { heading: "The release", body: "The 2026 edition returns Russell's Reserve 13 Year as a limited barrel-proof bourbon with commemorative packaging." },
      { heading: "Channel context", body: "The producer points to limited online, distillery visitor-center, and select-retailer availability rather than one synchronized national drop." },
      { heading: "Hunting context", body: "A spring edition can continue surfacing after its launch. Use timestamps and current fulfillment evidence instead of treating an undated listing as live stock." },
    ],
    sources: [{ label: "Russell's Reserve 13 Year Old Bourbon", url: "https://www.russellsreserve.com/en-us/our-products/13-year-old-bourbon/", type: "official" }],
  },
  {
    kind: "release",
    slug: "eh-taylor-four-grain-cured-oak-2026",
    eyebrow: "Limited release watch",
    title: "Buffalo Trace brings back E.H. Taylor Four Grain and Cured Oak",
    dek: "Two 10-year Bottled-in-Bond bourbons return together, with Four Grain joining the annual limited-release line.",
    summary: "Buffalo Trace announced the May 2026 return of E.H. Taylor Four Grain and Cured Oak. Both are 10-year, 100-proof Bottled-in-Bond releases; local allocation remains highly limited.",
    startDate: "2026-05",
    dateLabel: "May 2026 release",
    status: "watch",
    states: ["Kentucky"],
    bottle: "E.H. Taylor Four Grain and Cured Oak 2026",
    msrp: "$79.99 each",
    proof: "100 proof",
    availability: "Gift-shop and limited retail allocation",
    updatedAt: "2026-07-21",
    facts: [
      { label: "Expressions", value: "Four Grain and Cured Oak" },
      { label: "Age", value: "10 years" },
      { label: "Proof", value: "100 · Bottled-in-Bond" },
      { label: "Four Grain", value: "Returns as an annual limited release" },
    ],
    sections: [
      { heading: "What returned", body: "Four Grain combines corn, rye, wheat, and malted barley, while Cured Oak focuses on barrels built from unusually long-seasoned staves." },
      { heading: "Release context", body: "Both expressions returned in May through Buffalo Trace and limited retail channels. Four Grain is positioned to continue annually; Cured Oak remains a more singular return." },
      { heading: "Availability context", body: "An official relaunch does not imply broad shelf access. Gift-shop rules, state allocation, and current retailer evidence determine whether a bottle is actionable." },
    ],
    sources: [
      { label: "Buffalo Trace E.H. Taylor Four Grain", url: "https://www.buffalotracedistillery.com/our-brands/e-h-taylor-jr/e-h-taylor-jr-four-grain/", type: "official" },
      { label: "E.H. Taylor Cured Oak", url: "https://www.buffalotracedistillery.com/our-brands/e-h-taylor-jr/e-h-taylor-jr-cured-oak/", type: "official" },
      { label: "Buffalo Trace 2026 press release", url: "https://www.breakingbourbon.com/bourbon-whiskey-press-releases/buffalo-trace-distillery-reintroduces-two-iconic-colonel-e-h-taylor-jr-bourbons", type: "press" },
    ],
  },
  {
    kind: "release",
    slug: "woodford-reserve-double-double-oaked-2026",
    eyebrow: "Distillery release watch",
    title: "Woodford Reserve brings Double Double Oaked back for 2026",
    dek: "The distillery's extended double-barreled expression returns as a limited 2026 release.",
    summary: "Woodford Reserve's official store identifies the 2026 Double Double Oaked release and lists it as a limited distillery offering. Online status can change and does not establish inventory at other retailers.",
    startDate: "2026",
    dateLabel: "2026 distillery release",
    status: "watch",
    states: ["Kentucky"],
    bottle: "Woodford Reserve Double Double Oaked 2026",
    msrp: "$199.99",
    availability: "Limited distillery and online release",
    updatedAt: "2026-07-21",
    facts: [
      { label: "Edition", value: "2026" },
      { label: "Style", value: "Extended double-barreled bourbon" },
      { label: "Suggested retail", value: "$199.99" },
      { label: "Channel", value: "Official distillery store" },
    ],
    sections: [
      { heading: "Bottle profile", body: "Double Double Oaked extends the secondary-barrel maturation associated with Woodford Reserve Double Oaked for a richer limited expression." },
      { heading: "What is confirmed", body: "Woodford's official store identifies a 2026 edition and publishes its direct-sale status and price." },
      { heading: "Availability context", body: "A distillery-store listing is useful channel evidence, but stock status can change and does not prove another retailer has the bottle." },
    ],
    sources: [{ label: "Woodford Reserve 2026 Double Double Oaked", url: "https://shop.woodfordreserve.com/2026-double-double-oaked/", type: "official" }],
  },
];
