const {reconcileMemberRewards,summarizeMemberRewards}=require("../../../../src/lib/sighting-rewards.ts");
import React,{useEffect} from 'react';
import {Text} from 'react-native';
import glyphMap from '@expo/vector-icons/build/vendor/react-native-vector-icons/glyphmaps/MaterialCommunityIcons.json';
const query=new URLSearchParams(location.search);
export let routeParams:any={section:query.get('section')||'rewards',item:'sticker_pack'};
export const fixtureState={balance:130,redemptions:[] as any[],calls:[] as any[],failOnce:query.has('retry'),free:query.has('free'),featured:[] as string[]};
(globalThis as any).rewardFixture=fixtureState;
const catalog=[{key:'sticker_pack',name:'Bourbon Signal sticker pack',points:75,fulfillmentType:'physical',options:{usShippingIncluded:true}},{key:'rocks_glass',name:'Bourbon Signal rocks glass',points:400,fulfillmentType:'physical',options:{usShippingIncluded:true,glassQuantity:1,engravingPointsPerGlass:125}},{key:'glencairn',name:'Bourbon Signal Glencairn',points:500,fulfillmentType:'physical',options:{usShippingIncluded:true,glassQuantity:1,engravingPointsPerGlass:125}}];
const profile={customDisplayName:'Chandler',identity:{label:'Founder #1'},membership:{label:fixtureState.free?'Free':'Bottled in Bond',tier:fixtureState.free?'free':'bottled-in-bond'},entitlements:{fullFeed:true,canSubmitSignals:true}};
const badges=[{id:'first_sighting',label:'First Sighting',earnedAt:'2026-10-02T12:00:00Z',pointsAwarded:10},{id:'photo_finish',label:'Photo Finish',earnedAt:'2026-10-03T12:00:00Z',pointsAwarded:10}];
let address:any={recipientName:'Sample Member',addressLine1:'123 Example Street',addressLine2:null,city:'Louisville',stateCode:'KY',postalCode:'40202',phone:'+15025550100',status:'submitted'};
const receipts=new Map();
const api={getMemberProfile:async()=>({profile}),updateMemberProfile:async({displayName}:any)=>{profile.customDisplayName=displayName;return {profile};},getSignalPoints:async()=>({balance:fixtureState.balance,debt:0,tier:profile.membership.tier,redemptionEligible:!fixtureState.free,catalog,redemptions:fixtureState.redemptions,activity:[{id:'1',kind:'credit',points:20,balanceDelta:20,debtDelta:0,sourceType:'clerk_metadata',reason:'sighting_base_v4',createdAt:'2026-10-03T15:00:00Z'}]}),getAchievements:async()=>{if(new URLSearchParams(location.search).has("slow")) await new Promise(resolve=>setTimeout(resolve,12000));const sightings=Array.from({length:6},(_,i)=>({id:'fixture'+i,bottleId:'b'+i,bottleName:'Bottle '+i,storeId:'store'+(i%2),storeName:'Sample Store',storeCity:'Louisville',storeState:'KY',storeTimeZone:'America/New_York',sightingType:'seen_in_store' as const,rarityTier:'limited' as const,createdAt:i===0?'2026-09-07T15:00:00Z':i===1?'2026-09-14T15:00:00Z':'2026-10-03T15:00:00Z',...(i===0?{rewardState:{photoProof:{url:'https://example.test/photo',uploadedAt:'2026-09-07T15:00:00Z',status:'pending' as const}}}:{})}));const rewards=reconcileMemberRewards(sightings,undefined,'2026-10-03T16:00:00Z');return summarizeMemberRewards(sightings,rewards,{availabilityUpdates:2,qualifiedReferrals:0,featuredBadgeIds:fixtureState.featured});},saveFeaturedBadges:async(ids:string[])=>{fixtureState.featured=ids;return {ok:true,featuredBadgeIds:ids};},getReferralSummary:async()=>({referralLink:'https://example.test/r/DEMO',referralPoints:30,program:{pointsByTier:{free:10,standard:100,barrel:250,'bottled-in-bond':1500},freeAwardLimit:3,upgradeAwardsDifferenceOnly:true},referrals:{total:3,awarded:3,free:3,standard:0,barrel:0,founder:0}}),getRewardShipping:async()=>({record:address,defaultRecipientName:'Sample Member'}),saveRewardShipping:async(value:any)=>{address=value;return {record:address};},redeemReward:async(value:any)=>{fixtureState.calls.push(value);if(!receipts.has(value.idempotencyKey)){fixtureState.balance-=75;const result={ok:true,redemptionId:'fixture-redemption',status:'submitted',balance:fixtureState.balance};receipts.set(value.idempotencyKey,result);fixtureState.redemptions=[{id:result.redemptionId,itemKey:value.itemKey,pointsSpent:75,status:'submitted',createdAt:'2026-10-03T12:00:00Z',updatedAt:'2026-10-03T12:00:00Z'}];}if(fixtureState.failOnce){fixtureState.failOnce=false;throw new Error('Simulated lost response. Retry the same redemption.');}return receipts.get(value.idempotencyKey);},cancelReward:async()=>{fixtureState.redemptions[0].status='canceled';fixtureState.balance+=75;return {ok:true};}};
export function useMobileApi(){return api;}
export function useAuth(){return {userId:'account-preview-member',signOut:async()=>{}};}
function navigate(value:any){const path=typeof value==='string'?value:value.pathname;routeParams=value.params||{};globalThis.dispatchEvent(new CustomEvent('fixture-navigate',{detail:path.split('/').pop()}));}
const router={push:navigate,replace:navigate};
export const useRouter=()=>router;export const useLocalSearchParams=()=>routeParams;
export function useFocusEffect(fn:any){useEffect(fn,[fn]);}
export const getItemAsync=async(key:string)=>localStorage.getItem(key);
export const setItemAsync=async(key:string,value:string)=>localStorage.setItem(key,value);
export const deleteItemAsync=async(key:string)=>localStorage.removeItem(key);
export const randomUUID=()=>crypto.randomUUID();
export const signOutWithRadarPushDisabled=async()=>{};
export const runtimeVersion='fixture';export const updateId='fixture';
export default {nativeAppVersion:'fixture',nativeBuildVersion:'fixture'};
export function MaterialCommunityIcons({name,size,color}:any){return <Text accessible={false} style={{fontFamily:'MaterialCommunityIcons',fontSize:size,color}}>{String.fromCodePoint((glyphMap as any)[name]||983041)}</Text>;}
