'use client';
import MemberDirectory from './MemberDirectory';
import CatalogMaintenance from './CatalogMaintenance';
import FeedbackWorkspace from './FeedbackWorkspace';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import type { OwnerCoverage, OwnerMember, ReviewRow } from '../../../shared/owner-workspace';
import { coverageStatusLabels, type CoverageStatus } from '../../../shared/coverage-requests';
import type { CollectionPriceReference } from '@/lib/collection-value';
import AdminSightingsClient from '@/app/admin/sightings/AdminSightingsClient';
import AdminBottleQueueClient from '@/app/admin/bottle-queue/AdminBottleQueueClient';
import SignalPointRewardQueue from './SignalPointRewardQueue';
import styles from './AdminWorkspace.module.css';
type PricingBottle={id:string;name:string;members:number;reference:CollectionPriceReference|null};
async function request<T>(path:string,body?:unknown):Promise<T>{const response=await fetch(path,{cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Workspace request failed');return data;}
export default function AdminWorkspace(){
  const sequence=useRef(0);const [section,setSection]=useState('Overview');const [coverage,setCoverage]=useState<OwnerCoverage|null>(null);const [overview,setOverview]=useState<Record<string,unknown>|null>(null);const [members,setMembers]=useState<OwnerMember[]>([]);const [query,setQuery]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(false);const [pricing,setPricing]=useState<{bottles:PricingBottle[];history:Array<{id:number;bottle_id:string;review_note:string;reviewed_at:string}>;health:{checked_at:string;summary:{expiredMsrp:number;expiredSecondary:number;secondaryReviewDue:number;missingBoth:number}}|null}|null>(null);
  useEffect(()=>{const chosen=new URLSearchParams(window.location.search).get('section');if(chosen && ['Pricing','Coverage','Members','Bottles','Feedback'].includes(chosen))setSection(chosen);},[]);
  async function load(){const ticket=++sequence.current;setLoading(true);setError('');try{
    if(section==='Overview'){const data=await request<Record<string,unknown>>('/api/admin/overview');if(ticket===sequence.current)setOverview(data);}
    if(section==='Coverage'){const data=await request<OwnerCoverage>('/api/admin/coverage');if(ticket===sequence.current)setCoverage(data);}

    if(section==='Pricing'){const data=await request<NonNullable<typeof pricing>>('/api/admin/pricing');if(ticket===sequence.current)setPricing(data);}
  }catch(e){if(ticket===sequence.current)setError(e instanceof Error?e.message:'Workspace unavailable');}finally{if(ticket===sequence.current)setLoading(false);}}
  useEffect(()=>{void load();return()=>{sequence.current++;};},[section]);
  const groups=new Map<string,ReviewRow[]>();for(const row of coverage?.requests||[])groups.set(row.canonicalTargetKey||row.id,[...(groups.get(row.canonicalTargetKey||row.id)||[]),row]);
  return <main className={styles.workspace}><header><p className={styles.eyebrow}>BOURBON SIGNAL · OWNER</p><h1>Your admin workspace</h1><p>Review requests, help members and keep Bourbon Signal running.</p></header><nav>{['Overview','Members','Bottles','Community','Feedback','Coverage','Rewards','Pricing','Operations'].map(tab=><button key={tab} aria-pressed={section===tab} onClick={()=>setSection(tab)}>{tab}</button>)}</nav>{error?<p role="alert" className={styles.error}>{error}</p>:null}{loading?<p role="status">Refreshing workspace…</p>:null}
    {section==='Overview'?<><h2>Needs attention</h2><div className={styles.grid}>{[['Coverage','coverage'],['Community','community'],['Bottle submissions','bottles'],['Rewards','rewards'],['Founder shipments','founderShipping']].map(([label,key])=><button className={styles.metric} key={key} onClick={()=>key==='founderShipping'?window.location.assign('/admin/control-room#founder-glasses'):setSection(key==='bottles'?'Bottles':label)}><span>{label}</span><strong>{overview&&typeof overview[key]==='number'?String(overview[key]):'—'}</strong></button>)}</div>{Array.isArray(overview?.unavailable)&&overview.unavailable.length?<p>Some queues are unavailable. A dash does not mean zero.</p>:null}<div className={styles.links}><button onClick={()=>setSection('Pricing')}>Review pricing →</button><Link href="/admin/operations">Service health →</Link><Link href="/admin/control-room">Detailed company controls →</Link><Link href="/admin/retailers">Retailers →</Link></div></>:null}
    {section==='Coverage'?<><h2>Coverage inbox</h2><p>App and website requests appear together. Member updates show in request history; private notes stay here. Requested keeps investigation queued. Under review pauses automation for your review.</p>{[...groups.values()].sort((a,b)=>Number(b.some(r=>r.review?.priority==='high'))-Number(a.some(r=>r.review?.priority==='high'))||b.length-a.length).map(rows=><details key={rows[0].canonicalTargetKey} className={styles.card}><summary><strong>{rows[0].storeName||rows[0].areaLabel}, {rows[0].stateCode}</strong><span>{new Set(rows.map(r=>r.userId)).size} members · {coverageStatusLabels[rows[0].status as CoverageStatus]}</span></summary>{rows.map(row=><CoverageEditor key={row.id} row={row} onSaved={load}/>)}</details>)}{coverage?.requests.length===0?<p>No requests waiting for review.</p>:null}<h3>Automation progress</h3>{coverage?<p>{Object.entries(coverage.automation).map(([status,n])=>`${status.replaceAll('_',' ')}: ${n}`).join(' · ')||'No active coverage jobs.'}</p>:null}</>:null}
    {section==='Members'?<MemberDirectory/>:null}
    {section==='Community'?<AdminSightingsClient/>:null}
    {section==='Bottles'?<><CatalogMaintenance/><AdminBottleQueueClient/></>:null}
    {section==='Feedback'?<FeedbackWorkspace/>:null}
    {section==='Operations'?<div className={styles.links}><Link href='/admin/operations'>Service health</Link><Link href='/admin/control-room'>Audit history and company controls</Link></div>:null}
    {section==='Rewards'?<><SignalPointRewardQueue/><div className={styles.links}><Link href="/admin/control-room#founder-glasses">Founder glass fulfillment →</Link></div></>:null}
    {section==='Pricing'?<><h2>Pricing reviews</h2>{pricing?.health?<p>Daily check: {String(pricing.health.checked_at).slice(0,10)} · {pricing.health.summary.expiredMsrp} expired MSRP references · {pricing.health.summary.expiredSecondary} expired secondary references · {pricing.health.summary.secondaryReviewDue} secondary reviews due.</p>:<p>The first scheduled pricing check is pending.</p>}<p>Prioritize bottles on members’ shelves. Use exact release and size evidence. Retail asking prices do not establish MSRP or completed-sale value.</p>{pricing?<PriceEditor bottles={pricing.bottles} onSaved={load}/>:null}<h3>Recent reviews</h3>{pricing?.history.map(h=><article className={styles.card} key={h.id}><strong>{h.bottle_id}</strong><p>{h.review_note}</p><small>{String(h.reviewed_at).slice(0,10)}</small></article>)}</>:null}
    <button disabled={loading} onClick={()=>void load()}>Refresh</button>
  </main>;
}
function CoverageEditor({row,onSaved}:{row:ReviewRow;onSaved:()=>Promise<void>}){const [note,setNote]=useState(row.review?.internal_note||'');const [update,setUpdate]=useState(row.review?.member_update||'');const [status,setStatus]=useState(row.status);const [high,setHigh]=useState(row.review?.priority==='high');const [busy,setBusy]=useState(false);const [error,setError]=useState('');async function save(){setBusy(true);setError('');try{const response=await fetch('/api/admin/coverage',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:row.id,status,internalNote:note,memberUpdate:update,priority:high?'high':'normal'})});const data=await response.json();if(!response.ok)throw new Error(data.error);await onSaved();}catch(e){setError(e instanceof Error?e.message:'Save failed');}finally{setBusy(false);}}return <div className={styles.editor}><p>{coverageStatusLabels[row.status as CoverageStatus]} · Updated {row.updatedAt?.slice(0,10)}</p><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}>{row.status==='improved'?<option value="improved">Coverage improved (verified)</option>:null}{(['requested','on_radar','closed'] as const).map(st=><option key={st} value={st}>{coverageStatusLabels[st]}</option>)}</select></label><label>Private note<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={1000}/></label><label>Member update<textarea value={update} onChange={e=>setUpdate(e.target.value)} maxLength={500}/></label><label className={styles.check}><input type="checkbox" checked={high} onChange={e=>setHigh(e.target.checked)}/>High priority</label><p>Member preview: {update||'No update yet.'}</p>{error?<p role="alert">{error}</p>:null}<button disabled={busy||status==='improved'} onClick={()=>void save()}>{busy?'Saving…':'Save review'}</button></div>;}
function PriceEditor({bottles,onSaved}:{bottles:PricingBottle[];onSaved:()=>Promise<void>}){const [search,setSearch]=useState('');const [chosen,setChosen]=useState<PricingBottle|null>(null);const [amount,setAmount]=useState('');const [date,setDate]=useState('');const [source,setSource]=useState('');const [label,setLabel]=useState('');const [market,setMarket]=useState('');const [low,setLow]=useState('');const [high,setHigh]=useState('');const [marketDate,setMarketDate]=useState('');const [marketSource,setMarketSource]=useState('');const [note,setNote]=useState('');const [sales,setSales]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 function choose(b:PricingBottle){setChosen(b);setAmount(String(b.reference?.msrp?.amount||''));setDate(b.reference?.msrp?.date||'');setSource(b.reference?.msrp?.source||'');setLabel(b.reference?.msrp?.label||'');setLow(String(b.reference?.secondary?.low||''));setHigh(String(b.reference?.secondary?.high||''));setMarketDate(b.reference?.secondary?.date||'');setMarketSource(b.reference?.secondary?.source||'');setMarket(b.reference?.secondary?.label||'');setNote('');setSales(b.reference?.secondary?.observations?.map(o=>`${o.date}, ${o.amount}, ${o.source}`).join('\n')||'');setMessage('');}
 async function save(){if(!chosen)return;setBusy(true);setMessage('');try{const observations=sales.trim()?sales.trim().split('\n').map(line=>{const [date,amount,...url]=line.split(',');return {date:date.trim(),amount:Number(amount),source:url.join(',').trim()};}):undefined;await request('/api/admin/pricing',{reference:{bottleId:chosen.id,names:[chosen.name],...(amount?{msrp:{amount:Number(amount),date,source,label}}:{}),...(low||observations?{secondary:{low:Number(low)||1,high:Number(high)||1,date:marketDate,source:marketSource,label:market,evidenceKind:observations?'completed_sales':'market_reference',observations}}:{})},note});setMessage('Price review saved. The next shelf refresh uses this record.');await onSaved();}catch(e){setMessage(e instanceof Error?e.message:'Review failed');}finally{setBusy(false);}}
 const due=(b:PricingBottle)=>{const r=b.reference;return !r?'Missing prices':r.msrp&&Date.now()-Date.parse(r.msrp.date)>730*86400000?'MSRP expired':!r.secondary?'Secondary missing':Date.now()-Date.parse(r.secondary.date)>90*86400000?'Secondary expired':Date.now()-Date.parse(r.secondary.date)>60*86400000?'Review soon':!r.msrp?'MSRP missing':'References current';};
 return <><label>Find a bottle<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Bottle name"/></label><div className={styles.grid}>{bottles.filter(b=>b.name.toLowerCase().includes(search.toLowerCase())).slice(0,12).map(b=><button key={b.id} className={styles.metric} onClick={()=>choose(b)}><strong className={styles.bottleTitle}>{b.name}</strong><span>{b.members} members own this · {due(b)}</span></button>)}</div>{chosen?<div className={styles.card}><h3>{chosen.name}</h3><p>Exact catalog ID: {chosen.id}. Include edition and size in the source description. New records replace this bottle’s prior reference; history is retained.</p><div className={styles.grid}><label>Manufacturer MSRP<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Original MSRP date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Manufacturer source URL<input value={source} onChange={e=>setSource(e.target.value)}/></label><label>MSRP source, release and size<input value={label} onChange={e=>setLabel(e.target.value)}/></label><label>Secondary low<input inputMode="decimal" value={low} onChange={e=>setLow(e.target.value)}/></label><label>Secondary high<input inputMode="decimal" value={high} onChange={e=>setHigh(e.target.value)}/></label><label>Secondary observation date<input type="date" value={marketDate} onChange={e=>setMarketDate(e.target.value)}/></label><label>Secondary source URL<input value={marketSource} onChange={e=>setMarketSource(e.target.value)}/></label><label>Secondary source, release and size<input value={market} onChange={e=>setMarket(e.target.value)}/></label></div><label>Completed-sale evidence (optional)<textarea value={sales} onChange={e=>setSales(e.target.value)} placeholder="YYYY-MM-DD, price excluding fees, HTTPS sale URL"/></label><p>Use at least three distinct sales within 90 days, with the same edition, size and fee basis. The range is calculated from these observations and filters extreme outliers. Without sale evidence, a manual range is labeled a low-confidence market reference.</p><label>Review note<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="How did you verify the bottle match and prices?" maxLength={1000}/></label><button disabled={busy||note.trim().length<10} onClick={()=>void save()}>{busy?'Saving…':'Save reviewed prices'}</button><p role="status">{message}</p></div>:null}</>;
}
