// This file is generated by scripts/generate-state-lifecycle-types.mjs. Do not edit manually.

export const STATE_LIFECYCLE_CONFIG = {
  "activeStates": [
    "NC",
    "VA",
    "PA",
    "OH",
    "IA",
    "ID",
    "AL",
    "IL",
    "IN",
    "TN",
    "SC",
    "MD-MONTGOMERY",
    "KY",
    "AZ",
    "CA",
    "FL",
    "TX",
    "GA",
    "MI",
    "MN",
    "MO",
    "NV",
    "WA",
    "WI",
    "UT",
    "NY",
    "CO"
  ],
  "reliabilityPolicy": {
    "schemaVersion": 1,
    "refreshIntervalMs": 1800000,
    "refreshSafetyMarginMs": 300000,
    "defaultExpectedStateRunMs": 90000,
    "workerConcurrency": 4,
    "promotionPolicy": {
      "minShadowRuns": 3,
      "minCanaryRuns": 2,
      "requireVerticalSliceManifest": true,
      "requireFixtureContract": true,
      "requireCanaryPreviewUrl": true
    },
    "grandfatheredActiveStates": [
      "NC",
      "VA",
      "PA",
      "OH",
      "IA",
      "ID",
      "AL",
      "IL",
      "IN",
      "TN",
      "SC",
      "MD-MONTGOMERY",
      "KY",
      "AZ",
      "CA",
      "FL",
      "TX",
      "GA",
      "MI",
      "MN",
      "MO",
      "NV",
      "WA",
      "WI"
    ],
    "stateExpectedRunMs": {
      "TX": 420000,
      "VA": 240000,
      "IN": 240000,
      "TN": 180000,
      "SC": 180000,
      "KY": 180000
    }
  },
  "states": {
    "NC": {
      "customerLabel": "North Carolina",
      "sourceLabel": "North Carolina ABC + county boards",
      "publicStatus": "active",
      "lifecycle": "store_inventory_and_board_leads",
      "coverageTier": "live_store_inventory",
      "refinementLevel": "board",
      "customerSummary": "ABC board, warehouse, and selected county-board store signals where public sources support them. The Charlotte metro option expands deterministically to eight reviewed official boards; board-level rows remain leads, not exact shelf inventory.",
      "customerAreaLabel": "North Carolina ABC boards",
      "areaOptions": [
        "Charlotte Metro ABC Boards"
      ]
    },
    "VA": {
      "customerLabel": "Virginia",
      "sourceLabel": "Virginia ABC",
      "publicStatus": "active",
      "lifecycle": "store_inventory",
      "coverageTier": "live_store_inventory",
      "refinementLevel": "city",
      "customerSummary": "Virginia ABC store availability for normal products, with limited-availability caveats."
    },
    "PA": {
      "customerLabel": "Pennsylvania",
      "sourceLabel": "Pennsylvania FWGS / PLCB",
      "publicStatus": "active",
      "lifecycle": "store_inventory",
      "coverageTier": "live_store_inventory",
      "refinementLevel": "city_store",
      "customerSummary": "FWGS pickup/store inventory where public browser extraction confirms current store rows."
    },
    "OH": {
      "customerLabel": "Ohio",
      "sourceLabel": "Ohio OHLQ",
      "publicStatus": "active",
      "lifecycle": "store_inventory",
      "coverageTier": "live_store_inventory",
      "refinementLevel": "city",
      "customerSummary": "OHLQ browser-assisted store availability where the public source is reachable."
    },
    "IA": {
      "customerLabel": "Iowa",
      "sourceLabel": "Iowa ABD + Costco warehouse watch",
      "publicStatus": "active",
      "lifecycle": "store_delivery_leads",
      "coverageTier": "store_delivery_leads",
      "refinementLevel": "city",
      "inventoryAlertable": false,
      "watchAlertable": true,
      "customerSummary": "Official Iowa ABD delivery and allocation rows. These are strong store-level leads, not live shelf inventory. Costco warehouse bourbon signals are included where verified for Iowa warehouses."
    },
    "ID": {
      "customerLabel": "Idaho",
      "sourceLabel": "Idaho State Liquor Division",
      "publicStatus": "active",
      "lifecycle": "store_availability_status",
      "coverageTier": "store_availability_status",
      "refinementLevel": "city",
      "customerSummary": "Official Idaho Liquor store availability status and as-of-date rows by store/city. No bottle-count or reservation guarantee; verify before driving."
    },
    "AL": {
      "customerLabel": "Alabama",
      "sourceLabel": "Alabama ABC + Costco warehouse watch",
      "publicStatus": "active",
      "lifecycle": "scheduled_release_leads",
      "coverageTier": "shipment_drop_intelligence",
      "refinementLevel": "statewide",
      "customerSummary": "Official limited-release schedule and store/drop intelligence. Scheduled release leads, not live shelf inventory. Costco warehouse bourbon signals are included where verified for Alabama warehouses."
    },
    "IL": {
      "customerLabel": "Illinois",
      "sourceLabel": "Illinois Binny's + Costco + retailer inventory watch",
      "publicStatus": "active",
      "lifecycle": "retailer_store_inventory",
      "coverageTier": "live_store_inventory",
      "refinementLevel": "statewide",
      "customerSummary": "Whitelisted public retailer inventory rows with strict bourbon matching and verify-before-driving caveats. Costco warehouse bourbon signals are included alongside Illinois retailer inventory where verified."
    },
    "IN": {
      "customerLabel": "Indiana",
      "sourceLabel": "Indiana ATC + Costco + retailer inventory watch",
      "publicStatus": "active",
      "lifecycle": "retailer_store_inventory",
      "coverageTier": "live_store_inventory",
      "refinementLevel": "statewide",
      "customerSummary": "Verified retailer store inventory and pickup/orderability across Indiana, with exact-store identity and verify-before-driving caveats. ATC rows provide store-spine context only and are never bottle availability. Costco warehouse bourbon signals are included where verified."
    },
    "TN": {
      "customerLabel": "Tennessee",
      "sourceLabel": "Tennessee ABC + retailer inventory watch",
      "publicStatus": "active",
      "lifecycle": "retailer_store_inventory",
      "coverageTier": "live_store_inventory",
      "refinementLevel": "city_store",
      "customerSummary": "Whitelisted Tennessee retailer e-commerce inventory with exact host, merchant, address, product, safe-format, and current orderability binding. Binary availability never becomes an exact quantity; stable Nashville metro store identities remain discoverable even when no current row qualifies.",
      "customerAreaLabel": "Nashville Metro",
      "areaOptions": [
        "Nashville Metro"
      ]
    },
    "UT": {
      "customerLabel": "Utah",
      "sourceLabel": "Utah DABS",
      "publicStatus": "active",
      "lifecycle": "aggregate_inventory_watch",
      "coverageTier": "aggregate_inventory_watch",
      "refinementLevel": "statewide",
      "inventoryAlertable": false,
      "watchAlertable": false,
      "shadowEligible": true,
      "customerSummary": "DABS product locator, warehouse/store aggregate, allocated, and barrel-selection watch data. Not exact per-store shelf inventory yet.",
      "promotionStage": "active",
      "promotionEvidence": {
        "shadowRuns": 3,
        "canaryRuns": 2,
        "verifiedAt": "2026-07-17T00:14:48.000Z",
        "shadowArtifact": "engine/out/shadow/UT (three successful bounded runs on 2026-07-16; alerts disabled and production untouched)",
        "canaryArtifact": "engine/out/canary/UT/site-run1 and site-run2 (two coherent canary builds with a Utah partition and zero Utah delivery alerts)",
        "canaryPreviewUrl": "https://great-socks-sell.loca.lt",
        "verticalSliceManifest": "engine/data/state-integration/UT.json",
        "fixtureContract": "engine/data/state-fixtures/UT.json",
        "immutableEvidence": {
          "schemaVersion": 1,
          "state": "UT",
          "generatedAt": "2026-07-17T00:14:48.000Z",
          "sourceConfigHash": "3c27a45ba71304c88a4989338aa33b90c7159be1d46829cb36560dd595869203",
          "previewUrl": "https://great-socks-sell.loca.lt",
          "shadowRuns": [
            {
              "runId": "2026-07-16T22-48-16-026Z",
              "status": "success",
              "artifactHash": "2f5c30af05508458ef7415bb7ae3579121aae774cb41a1b85339636c565bd1ca"
            },
            {
              "runId": "2026-07-16T22-48-44-478Z",
              "status": "success",
              "artifactHash": "b15b9a88aa70b669442c9c6afa04de7677d6668aafa8ee128e5ba0db929a7438"
            },
            {
              "runId": "2026-07-16T22-49-07-044Z",
              "status": "success",
              "artifactHash": "4c1b9702ea0c41badccdd1dc8d80cfcdac53c5a184e097d25b64d10278451694"
            }
          ],
          "canaryRuns": [
            {
              "runId": "site-run1",
              "status": "success",
              "artifactHash": "85c6e184962728faf44f2205916a0f63283b72e1a9833fe50c8f6cf07bac9fec"
            },
            {
              "runId": "site-run2",
              "status": "success",
              "artifactHash": "85c6e184962728faf44f2205916a0f63283b72e1a9833fe50c8f6cf07bac9fec"
            }
          ],
          "provenance": {
            "repository": "tarsagent22/Bourbon-Signal",
            "workflowRunId": "29545745479",
            "workflowRunUrl": "https://github.com/tarsagent22/Bourbon-Signal/actions/runs/29545745479",
            "commitSha": "58801890ca7436711b9b21953d76caf0a242a440",
            "artifactId": "8393888338",
            "artifactName": "state-promotion-provenance-UT-29545745479",
            "artifactDigest": "4a90ad38c6fad757cff1d146c7f5284da6df5d2f0783a739065dbf3c60e2932d",
            "bundleDigest": "80faac8b215184f71a0c18ab57d1a93fa20dfcdc53767f4efc56e698ab452d2f",
            "status": "success"
          }
        }
      }
    },
    "MD-MONTGOMERY": {
      "customerLabel": "Maryland",
      "sourceLabel": "Montgomery County ABS",
      "customerAreaLabel": "Montgomery County",
      "areaOptions": [
        "Montgomery County"
      ],
      "publicStatus": "active",
      "lifecycle": "county_aggregate_inventory_watch",
      "coverageTier": "aggregate_inventory_watch",
      "refinementLevel": "area",
      "inventoryAlertable": false,
      "watchAlertable": false,
      "customerSummary": "Maryland coverage currently starts with Montgomery County ABS aggregate inventory and HAL program data. Exact per-store drilldown is a hardening target."
    },
    "OR": {
      "customerLabel": "Oregon",
      "sourceLabel": "Oregon OLCC / Oregon Liquor Search",
      "publicStatus": "research_only",
      "shadowEligible": true,
      "lifecycle": "blocked_store_inventory_research",
      "coverageTier": "blocked",
      "refinementLevel": "store",
      "customerSummary": "Research-only until Oregon Liquor Search browser/session collection reliably produces current store rows."
    },
    "NH": {
      "customerLabel": "New Hampshire",
      "sourceLabel": "New Hampshire Liquor & Wine Outlets",
      "publicStatus": "research_only",
      "shadowEligible": true,
      "lifecycle": "blocked_catalog_research",
      "coverageTier": "blocked",
      "refinementLevel": "store",
      "customerSummary": "Research-only until NHLC outlet/product data can be accessed reliably without Cloudflare/Turnstile failures."
    },
    "FL": {
      "customerLabel": "Florida",
      "sourceLabel": "Florida retailer inventory watch",
      "customerAreaLabel": "Florida retailer areas",
      "areaOptions": [
        "Tampa",
        "Clearwater",
        "Largo",
        "Saint Petersburg",
        "Pinellas Park",
        "Brandon",
        "Riverview",
        "Wesley Chapel",
        "Lutz",
        "Dunedin",
        "Oldsmar",
        "Palm Harbor",
        "Seminole",
        "Tarpon Springs",
        "Orlando",
        "Kissimmee",
        "Davenport",
        "Groveland",
        "Clermont",
        "Miami",
        "North Miami",
        "Hialeah",
        "Surfside",
        "Fort Lauderdale",
        "Hollywood",
        "Hallandale Beach",
        "Pembroke Pines",
        "Miramar",
        "Pompano Beach",
        "Sunrise",
        "West Palm Beach",
        "Jacksonville",
        "Sarasota",
        "Gainesville",
        "Pensacola",
        "Gulf Breeze",
        "Fort Walton Beach",
        "Destin",
        "Crestview",
        "Panama City Beach"
      ],
      "publicStatus": "active",
      "lifecycle": "retailer_store_inventory",
      "coverageTier": "live_store_inventory",
      "refinementLevel": "city_store",
      "customerSummary": "Guarded first-party Florida retailer inventory across Tampa Bay, Central Florida, South Florida, Jacksonville, Sarasota, Gainesville, and the Panhandle, with exact merchant/store identity, current retailer-reported quantity or binary orderability when observed, and verify-before-driving caveats."
    },
    "TX": {
      "customerLabel": "Texas",
      "sourceLabel": "Texas retailer inventory watch",
      "publicStatus": "active",
      "lifecycle": "retailer_store_inventory",
      "coverageTier": "live_store_inventory",
      "refinementLevel": "city_store",
      "customerSummary": "Guarded first-party Texas retailer inventory across multiple regions, with exact-store identity and verify-before-driving caveats. TABC and retailer catalog/event pages remain non-inventory context."
    },
    "GA": {
      "customerLabel": "Georgia",
      "sourceLabel": "Georgia retailer inventory + Costco warehouse watch",
      "publicStatus": "active",
      "lifecycle": "retailer_store_inventory",
      "coverageTier": "live_store_inventory",
      "refinementLevel": "city_store",
      "customerSummary": "Guarded first-party retailer signals from exact Georgia storefront identities, including a stable Atlanta metro store universe, plus Costco warehouse bourbon watch where verified. Binary orderability is kept distinct from retailer-reported quantity, and every store signal includes a verify before driving caveat.",
      "customerAreaLabel": "Atlanta Metro",
      "areaOptions": [
        "Atlanta Metro"
      ]
    },
    "KY": {
      "customerLabel": "Kentucky",
      "sourceLabel": "Kentucky distillery drops + Costco warehouse watch",
      "publicStatus": "active",
      "lifecycle": "distillery_drop_release_watch",
      "coverageTier": "distillery_release_watch",
      "refinementLevel": "distillery",
      "customerSummary": "Official Kentucky distillery gift-shop/drop and release-watch signals from Buffalo Trace, Old Forester, Four Roses, Heaven Hill, Maker's Mark, and Wild Turkey. Distillery pickup/release leads are clearly separated from retailer store shipment or inventory alerts. Costco warehouse bourbon signals are included where verified for Kentucky warehouses."
    },
    "SC": {
      "customerLabel": "South Carolina",
      "sourceLabel": "South Carolina Costco + retailer inventory mesh",
      "publicStatus": "active",
      "lifecycle": "retailer_store_inventory",
      "coverageTier": "live_store_inventory",
      "refinementLevel": "area",
      "customerAreaLabel": "South Carolina retailer areas",
      "areaOptions": [
        "Myrtle Beach",
        "North Myrtle Beach",
        "Conway",
        "Carolina Forest",
        "Surfside Beach",
        "Murrells Inlet",
        "Columbia",
        "Greenville",
        "Mauldin",
        "Simpsonville",
        "Taylors",
        "Landrum",
        "Spartanburg",
        "Charleston",
        "Mount Pleasant",
        "North Charleston",
        "Summerville",
        "Hilton Head Island",
        "Bluffton",
        "Indian Land",
        "Rock Hill"
      ],
      "customerSummary": "Whitelisted public South Carolina retailer inventory rows with verify-before-driving caveats. DOR ABL pages remain licensing/regulatory context only. Costco warehouse bourbon signals are included alongside South Carolina retailer inventory where verified."
    },
    "AZ": {
      "customerLabel": "Arizona",
      "sourceLabel": "Arizona Costco warehouse bourbon watch",
      "publicStatus": "active",
      "lifecycle": "costco_warehouse_inventory_watch",
      "coverageTier": "retailer_warehouse_inventory",
      "refinementLevel": "warehouse",
      "customerSummary": "Costco warehouse bourbon signals for Arizona warehouses where verified. Costco is treated as an in-state retailer source with fast-moving inventory caveats."
    },
    "CA": {
      "customerLabel": "California",
      "sourceLabel": "California first-party retailer availability + Costco warehouse watch",
      "customerAreaLabel": "California retailer areas",
      "areaOptions": [
        "San Diego"
      ],
      "publicStatus": "active",
      "lifecycle": "retailer_store_inventory",
      "coverageTier": "live_store_inventory",
      "refinementLevel": "area",
      "customerSummary": "First-party San Diego retailer pickup availability with exact store identity and verify-before-driving caveats. Online catalog-only sources remain watch-only; Costco warehouse signals stay a separate fast-moving availability lane."
    },
    "CO": {
      "customerLabel": "Colorado",
      "sourceLabel": "Denver Metro first-party retailer inventory",
      "customerAreaLabel": "Denver Metro",
      "areaOptions": [
        "Denver Metro"
      ],
      "publicStatus": "active",
      "lifecycle": "retailer_store_inventory",
      "coverageTier": "live_store_inventory",
      "refinementLevel": "city",
      "customerSummary": "Verified first-party retailer store inventory in Denver Metro, currently limited to Denver, Lakeside, Westminster, and Greenwood Village signals. This metro-scoped coverage does not imply statewide Colorado availability; verify before driving.",
      "promotionStage": "active",
      "shadowEligible": true,
      "promotionEvidence": {
        "shadowRuns": 3,
        "canaryRuns": 2,
        "verifiedAt": "2026-07-24T04:26:32.371Z",
        "shadowArtifact": "engine/data/state-evidence/CO/shadow-runs.json",
        "canaryArtifact": "engine/data/state-evidence/CO/canary-runs.json",
        "canaryPreviewUrl": "https://github.com/tarsagent22/Bourbon-Signal/actions/runs/30067755884",
        "verticalSliceManifest": "engine/data/state-integration/CO.json",
        "fixtureContract": "engine/data/state-fixtures/CO.json",
        "immutableEvidence": {
          "schemaVersion": 1,
          "state": "CO",
          "generatedAt": "2026-07-24T04:50:06.702Z",
          "sourceConfigHash": "8da37e44f93fbec7c3cf86cbfa33e78f4b092134d7416dd0cd6bd6ad6c84456b",
          "previewUrl": "https://github.com/tarsagent22/Bourbon-Signal/actions/runs/30067755884",
          "shadowRuns": [
            {
              "runId": "local-shadow-co-1",
              "status": "success",
              "generatedAt": "2026-07-24T03:12:27.082751Z",
              "artifactPath": "out/shadow/CO/local-evidence/report-1.json",
              "artifactHash": "787571f238aaee104ae0160b0b1071119c23b9cb14d3e73e37f10b84c15fc77f",
              "signalCount": 18,
              "sourceChains": [
                "bonnie-brae-liquor",
                "mollys-spirits",
                "total-beverage"
              ],
              "roadblockCount": 0,
              "alertsDisabled": true,
              "productionSnapshotTouched": false
            },
            {
              "runId": "local-shadow-co-2",
              "status": "success",
              "generatedAt": "2026-07-24T03:12:30.680259Z",
              "artifactPath": "out/shadow/CO/local-evidence/report-2.json",
              "artifactHash": "ba363c4766de7880c84bcbd386b2bfc50c8138222c539635fa353b81a9044e59",
              "signalCount": 18,
              "sourceChains": [
                "bonnie-brae-liquor",
                "mollys-spirits",
                "total-beverage"
              ],
              "roadblockCount": 0,
              "alertsDisabled": true,
              "productionSnapshotTouched": false
            },
            {
              "runId": "local-shadow-co-3",
              "status": "success",
              "generatedAt": "2026-07-24T03:12:34.055961Z",
              "artifactPath": "out/shadow/CO/local-evidence/report-3.json",
              "artifactHash": "410b0b8e3de41cde19219a4581033553606b2ccace1178fc9200791b576081bf",
              "signalCount": 18,
              "sourceChains": [
                "bonnie-brae-liquor",
                "mollys-spirits",
                "total-beverage"
              ],
              "roadblockCount": 0,
              "alertsDisabled": true,
              "productionSnapshotTouched": false
            }
          ],
          "canaryRuns": [
            {
              "runId": "local-canary-v2-co-1",
              "status": "success",
              "generatedAt": "2026-07-24T04:23:19.632762Z",
              "artifactHash": "f0cdbe330d2d77869e0c3fd761d6eeb2c44306fba7efd7a7869524bbf6584922"
            },
            {
              "runId": "local-canary-v2-co-2",
              "status": "success",
              "generatedAt": "2026-07-24T04:23:20.159223Z",
              "artifactHash": "214088eb8f52f02f13bbdcca5fa0f2159921592b63ff93b01b7a1aea8de43869"
            }
          ],
          "provenance": {
            "status": "success",
            "repository": "tarsagent22/Bourbon-Signal",
            "workflowFile": ".github/workflows/state-promotion-provenance.yml",
            "workflowName": "Verify state promotion provenance",
            "workflowRunId": "30067755884",
            "workflowRunAttempt": "1",
            "workflowRunUrl": "https://github.com/tarsagent22/Bourbon-Signal/actions/runs/30067755884",
            "commitSha": "8ff436d7e6066bd5b9ee86085c17c9e57d947619",
            "artifactId": "8586850690",
            "artifactName": "state-promotion-provenance-CO-30067755884",
            "artifactDigest": "ec6ad0295ee15416895e8c9d6baf23754fcd6e5d4c0294d17a35ae2416ba8dfb",
            "bundleDigest": "cb8a6e9d48fb3450ebb178dfbecc9716980fdfa05d4d8b464bbc3e42e2c44f6e",
            "generatedAt": "2026-07-24T04:49:16.814Z"
          }
        }
      }
    },
    "MI": {
      "customerLabel": "Michigan",
      "sourceLabel": "Michigan Costco warehouse bourbon watch",
      "publicStatus": "active",
      "lifecycle": "costco_warehouse_inventory_watch",
      "coverageTier": "retailer_warehouse_inventory",
      "refinementLevel": "warehouse",
      "customerSummary": "Costco warehouse bourbon signals for Michigan warehouses where verified. Costco is treated as an in-state retailer source with fast-moving inventory caveats."
    },
    "MN": {
      "customerLabel": "Minnesota",
      "sourceLabel": "Minnesota Costco warehouse bourbon watch",
      "publicStatus": "active",
      "lifecycle": "costco_warehouse_inventory_watch",
      "coverageTier": "retailer_warehouse_inventory",
      "refinementLevel": "warehouse",
      "customerSummary": "Costco warehouse bourbon signals for Minnesota warehouses where verified. Costco is treated as an in-state retailer source with fast-moving inventory caveats."
    },
    "MO": {
      "customerLabel": "Missouri",
      "sourceLabel": "Missouri Costco warehouse bourbon watch",
      "publicStatus": "active",
      "lifecycle": "costco_warehouse_inventory_watch",
      "coverageTier": "retailer_warehouse_inventory",
      "refinementLevel": "warehouse",
      "customerSummary": "Costco warehouse bourbon signals for Missouri warehouses where verified. Costco is treated as an in-state retailer source with fast-moving inventory caveats."
    },
    "MS": {
      "customerLabel": "Mississippi",
      "sourceLabel": "Mississippi statewide directory + selected retailer research",
      "publicStatus": "research_only",
      "lifecycle": "hybrid_directory_retailer_research",
      "coverageTier": "known_directory_selected_storefronts",
      "refinementLevel": "region_city_store",
      "areaOptions": [
        "Northwest / DeSoto–Memphis fringe",
        "North Central / Oxford",
        "Northeast / Tupelo–Golden Triangle",
        "Delta / Greenville–Clarksdale–Greenwood",
        "Central / Jackson–Madison–Rankin",
        "East Central / Meridian",
        "Pine Belt / Hattiesburg–Laurel",
        "Gulf Coast / Gulfport–Biloxi–Pascagoula",
        "Southwest / Natchez–Brookhaven–McComb–Vicksburg"
      ],
      "promotionStage": "research_only",
      "shadowEligible": true,
      "inventoryAlertable": false,
      "watchAlertable": false,
      "coverageLayerCounts": {
        "known": 690,
        "probeable": 2,
        "catalogWatch": 0,
        "live": 0,
        "alertGrade": 0
      },
      "customerSummary": "Research-only Mississippi foundation: all 690 current Package Retailer permits are known. Two exact first-party storefronts are probeable; two additional exact storefront identities are source-policy-blocked. No Mississippi alerts or active inventory coverage are authorized."
    },
    "NV": {
      "customerLabel": "Nevada",
      "sourceLabel": "Nevada first-party retailer inventory + Costco watch",
      "publicStatus": "active",
      "lifecycle": "retailer_store_inventory",
      "coverageTier": "live_store_inventory",
      "refinementLevel": "area",
      "areaOptions": [
        "Las Vegas Valley",
        "Reno–Sparks"
      ],
      "customerSummary": "First-party retailer store availability and pickup orderability across Las Vegas Valley and Reno–Sparks. Binary availability is not an exact shelf count; verify before driving. Costco remains a separate warehouse watch lane."
    },
    "NY": {
      "customerLabel": "New York",
      "sourceLabel": "New York City first-party retailer inventory",
      "customerAreaLabel": "New York City",
      "areaOptions": [
        "New York City"
      ],
      "publicStatus": "active",
      "lifecycle": "retailer_store_inventory",
      "coverageTier": "live_store_inventory",
      "refinementLevel": "city",
      "customerSummary": "Verified first-party retailer store inventory in New York City, limited to New York, Manhattan, Brooklyn, Queens, Bronx, and Staten Island location signals. This metro-scoped coverage does not imply statewide New York availability; verify before driving.",
      "promotionStage": "active",
      "shadowEligible": true,
      "promotionEvidence": {
        "shadowRuns": 3,
        "canaryRuns": 2,
        "verifiedAt": "2026-07-24T04:26:31.660Z",
        "shadowArtifact": "engine/data/state-evidence/NY/shadow-runs.json",
        "canaryArtifact": "engine/data/state-evidence/NY/canary-runs.json",
        "canaryPreviewUrl": "https://github.com/tarsagent22/Bourbon-Signal/actions/runs/30067754269",
        "verticalSliceManifest": "engine/data/state-integration/NY.json",
        "fixtureContract": "engine/data/state-fixtures/NY.json",
        "immutableEvidence": {
          "schemaVersion": 1,
          "state": "NY",
          "generatedAt": "2026-07-24T04:50:06.701Z",
          "sourceConfigHash": "ef15a51a0ba26e8e810945d0d0661107b130473abfb023aa08891a98c6e91287",
          "previewUrl": "https://github.com/tarsagent22/Bourbon-Signal/actions/runs/30067754269",
          "shadowRuns": [
            {
              "runId": "local-shadow-ny-1",
              "status": "success",
              "generatedAt": "2026-07-24T03:12:13.840404Z",
              "artifactPath": "out/shadow/NY/local-evidence/report-1.json",
              "artifactHash": "12646ea166f6573700701e23f25947c48e68b008ed49ad94f98add45cd6ce3a3",
              "signalCount": 11,
              "sourceChains": [
                "broadway-spirits",
                "cellar-53",
                "flatiron-wines"
              ],
              "roadblockCount": 0,
              "alertsDisabled": true,
              "productionSnapshotTouched": false
            },
            {
              "runId": "local-shadow-ny-2",
              "status": "success",
              "generatedAt": "2026-07-24T03:12:19.181839Z",
              "artifactPath": "out/shadow/NY/local-evidence/report-2.json",
              "artifactHash": "2df45c6f590b51b1053bdddc0cde11ca0e0f5947a2b6eae8f339c34ab4b460b3",
              "signalCount": 11,
              "sourceChains": [
                "broadway-spirits",
                "cellar-53",
                "flatiron-wines"
              ],
              "roadblockCount": 0,
              "alertsDisabled": true,
              "productionSnapshotTouched": false
            },
            {
              "runId": "local-shadow-ny-3",
              "status": "success",
              "generatedAt": "2026-07-24T03:12:23.568513Z",
              "artifactPath": "out/shadow/NY/local-evidence/report-3.json",
              "artifactHash": "28fcc26fd47be8e4f44f1c117a594a8e425ffb52500034ae432c6227a584d1cd",
              "signalCount": 11,
              "sourceChains": [
                "broadway-spirits",
                "cellar-53",
                "flatiron-wines"
              ],
              "roadblockCount": 0,
              "alertsDisabled": true,
              "productionSnapshotTouched": false
            }
          ],
          "canaryRuns": [
            {
              "runId": "local-canary-v2-ny-1",
              "status": "success",
              "generatedAt": "2026-07-24T04:23:18.583232Z",
              "artifactHash": "e90e53439c5d1302791a68b28b0648dc14405cdc1d8435191cf0af1919609c19"
            },
            {
              "runId": "local-canary-v2-ny-2",
              "status": "success",
              "generatedAt": "2026-07-24T04:23:19.106600Z",
              "artifactHash": "273a03c7b9a7504a93364cf885fc14f677b9b5534668d7dd8c747ba1d259bbd1"
            }
          ],
          "provenance": {
            "status": "success",
            "repository": "tarsagent22/Bourbon-Signal",
            "workflowFile": ".github/workflows/state-promotion-provenance.yml",
            "workflowName": "Verify state promotion provenance",
            "workflowRunId": "30067754269",
            "workflowRunAttempt": "1",
            "workflowRunUrl": "https://github.com/tarsagent22/Bourbon-Signal/actions/runs/30067754269",
            "commitSha": "8ff436d7e6066bd5b9ee86085c17c9e57d947619",
            "artifactId": "8586850796",
            "artifactName": "state-promotion-provenance-NY-30067754269",
            "artifactDigest": "35103018b362c11faebdff7d5fa3fd0298b46c14a6f5add7ea3c257190c02a15",
            "bundleDigest": "c4b4912ea7ef94c22e84de146ed91cfe4ad3c1795c82dda85cba6a82160e5b25",
            "generatedAt": "2026-07-24T04:49:17.264Z"
          }
        }
      }
    },
    "WA": {
      "customerLabel": "Washington",
      "sourceLabel": "Washington Costco warehouse bourbon watch",
      "publicStatus": "active",
      "lifecycle": "costco_warehouse_inventory_watch",
      "coverageTier": "retailer_warehouse_inventory",
      "refinementLevel": "warehouse",
      "customerSummary": "Costco warehouse bourbon signals for Washington warehouses where verified. Costco is treated as an in-state retailer source with fast-moving inventory caveats."
    },
    "WI": {
      "customerLabel": "Wisconsin",
      "sourceLabel": "Wisconsin Costco warehouse bourbon watch",
      "publicStatus": "active",
      "lifecycle": "costco_warehouse_inventory_watch",
      "coverageTier": "retailer_warehouse_inventory",
      "refinementLevel": "warehouse",
      "customerSummary": "Costco warehouse bourbon signals for Wisconsin warehouses where verified. Costco is treated as an in-state retailer source with fast-moving inventory caveats."
    }
  }
} as const;

export type StateLifecycleConfig = typeof STATE_LIFECYCLE_CONFIG;
export type ActiveStateCode = StateLifecycleConfig["activeStates"][number];
export type StateLifecycleEntry = StateLifecycleConfig["states"][keyof StateLifecycleConfig["states"]];
