// Generated by scripts/prepare-label-free-art.py from reviewed provenance.
export const LABEL_FREE_ARTWORK = {
  'eagle': require('../../assets/bottles/label-free-v1/bare-eagle.png'),
  'taylor': require('../../assets/bottles/label-free-v1/bare-taylor.png'),
  'michters': require('../../assets/bottles/label-free-v1/bare-michters.png'),
  'stagg': require('../../assets/bottles/label-free-v1/bare-stagg.png'),
  'blantons': require('../../assets/bottles/label-free-v1/bare-blantons.png'),
  'buffalo-trace': require('../../assets/bottles/label-free-v2/bare-buffalo-trace.png'),
  '1792': require('../../assets/bottles/label-free-v2/bare-1792.png'),
  'elijah-craig': require('../../assets/bottles/label-free-v2/bare-elijah-craig.png'),
  'knob-creek': require('../../assets/bottles/label-free-v2/bare-knob-creek.png'),
  'woodford-reserve': require('../../assets/bottles/label-free-v2/bare-woodford-reserve.png'),
  'woodford-double-oaked': require('../../assets/bottles/label-free-v2/bare-woodford-double-oaked.png'),
  'makers-mark': require('../../assets/bottles/label-free-v2/bare-makers-mark.png'),
  'makers-mark-46': require('../../assets/bottles/label-free-v2/bare-makers-mark-46.png'),
  'four-roses-single-barrel': require('../../assets/bottles/label-free-v2/bare-four-roses-single-barrel.png'),
  'four-roses-small-batch': require('../../assets/bottles/label-free-v2/bare-four-roses-small-batch.png'),
} as const;
