import Link from 'next/link';
import {PAID_MEMBERSHIP_PLANS} from '@/lib/membership-plan-catalog';
import type {PublicMarketingDrop} from '@/lib/public-marketing-feed';
import styles from './AppFunnel.module.css';
export default function AppFunnel({launch,feed}:{launch:{downloadUrl:string|null;transitionActive:boolean};feed:{drops:PublicMarketingDrop[];unavailable:boolean}}){
 const ready=launch.transitionActive&&launch.downloadUrl;
 const cta=<a className={styles.primary} href={ready?launch.downloadUrl!:'#app'}>{ready?'Download for iPhone':'Explore the iPhone app'} <span aria-hidden="true">↗</span></a>;
 return <div className={styles.site}><div className={styles.preview}>{ready?'Bourbon Signal for iPhone':'Website preview · iPhone launch pending'} · <Link href="/web-access">Existing member access</Link></div><header className={styles.header}><Link className={styles.wordmark} href="/">B<span>·</span>S <i>Bourbon Signal</i></Link><nav aria-label="Main navigation"><a href="#drops">Drop feed</a><a href="#membership">Membership</a><Link href="/coverage">Coverage</Link><Link href="/support">Support</Link><Link href="/settings">Account & billing</Link></nav></header>
 <main><section className={styles.hero} id="app"><div><p className={styles.eyebrow}>FOR THE HUNT. FOR YOUR SHELF.</p><h1>A better signal.<br/><em>A better bourbon hunt.</em></h1><p className={styles.intro}>Find meaningful bottle activity, follow the areas you care about, and build a collection that feels like yours.</p><div className={styles.actions}>{cta}<a className={styles.secondary} href="#drops">See the signal ↓</a></div><p className={styles.note}>{ready?'Free membership. One account across app and website.':'The iPhone app is preparing for public release. Existing web tools remain available until there is a verified public download.'}</p></div><figure className={styles.heroPhone}><div className={styles.phone}><img src="/app-marketing/home-sample.png" alt="Bourbon Signal app Home screen with state selection, bottle search and drop cards" width="390" height="844"/></div><figcaption>App screen preview · illustrative activity, not live stock</figcaption></figure></section>
 <section className={styles.featureBand}><div><span>01 / DISCOVER</span><h2>Turn activity into a lead.</h2><p>The app brings bottle search, market filters and member sightings together. Check the source and freshness before making a trip.</p></div><div><span>02 / WATCH</span><h2>Keep your hunt focused.</h2><p>Choose the areas and bottles you watch. Paid memberships add matching inbox and push alerts. Barrel Proof adds community sighting alerts.</p></div><div><span>03 / COLLECT</span><h2>Make your shelf personal.</h2><p>Track your bottles, ratings and notes. Explore your collection with Bourbon DNA and personalized intelligence on Barrel Proof.</p></div></section>
 <section className={styles.feed} id="drops"><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>A GLIMPSE OF THE SIGNAL</p><h2>Recent public bottle activity</h2></div>{cta}</div><p>This read-only preview shows publicly visible activity at state level. Exact details and member tools live in the app. A report is a lead, not a promise of availability.</p><div className={styles.dropGrid}>{feed.drops.map(d=><article key={d.id}><div className={styles.dropMeta}><span>{d.state}</span><span>{d.observedAt?new Date(d.observedAt).toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'America/New_York'}):'Recent activity'}</span></div><h3>{d.bottle}</h3><p>Public market activity</p></article>)}</div>{!feed.drops.length?<div className={styles.empty}>{feed.unavailable?'The public feed is temporarily unavailable. Please check back soon.':'No recent public activity to show. Quiet markets stay quiet here.'}</div>:null}</section>
 <section className={styles.collection}><figure><div className={styles.shelfPhone}><img src="/app-marketing/shelf-sample.png" alt="App My Shelf screen showing bottle highlights, collection artwork and ratings" width="1280" height="720"/></div><figcaption>App screen preview · sample collection</figcaption></figure><div><p className={styles.eyebrow}>YOUR COLLECTION, IN YOUR POCKET</p><h2>Remember the bottles.<br/><em>Discover your taste.</em></h2><p>From the first bottle to the shelf you have been building for years, keep your tasting notes, ratings and collection together. Your existing shelf comes with your account.</p>{cta}</div></section>
 <section className={styles.coverage}><p className={styles.eyebrow}>HONEST COVERAGE</p><h2>Useful where we have evidence.<br/>Clear where we don’t.</h2><p>Coverage varies by market, retailer and source. Some signals identify an exact store; others describe a wider market or release. We show the difference, and never guarantee stock.</p><Link className={styles.secondary} href="/coverage">Explore current coverage ↗</Link></section>
 <section className={styles.membership} id="membership"><p className={styles.eyebrow}>START FREE. UPGRADE WHEN IT HELPS.</p><h2>A membership for your kind of hunt.</h2><p>No new time-limited paid trials. Existing trials and earned, gifted or founder access keep their terms.</p><div className={styles.plans}><article><p className={styles.eyebrow}>YOUR STARTING POINT</p><h3>Free</h3><strong>$0 <small>always</small></strong><p>Explore public activity, participate in the community and start your shelf.</p><ul><li>Preview feed and member sightings</li><li>Post sightings and contribute missing bottles</li><li>My Shelf for up to 10 bottles</li><li>Keep one account when you upgrade</li></ul><Link className={styles.secondary} href="/sign-up">Create a Free account ↗</Link></article>{PAID_MEMBERSHIP_PLANS.map(p=><article key={p.tier} className={p.featured?styles.featured:''}><p className={styles.eyebrow}>{p.eyebrow}</p><h3>{p.name}</h3><strong>{p.monthlyPrice || p.oneTimePrice}<small>{p.monthlyPrice?' / month':' once'}</small></strong><p>{p.description}</p><ul>{p.features.map(f=><li key={f}>{f}</li>)}</ul><Link className={styles.secondary} href="/pricing">Compare & manage plans ↗</Link></article>)}</div><p className={styles.note}>App Store prices are shown in your local currency in the app. Apple purchases are managed through Apple; website subscriptions through Stripe. Sign in to your existing account to keep your access and avoid a second subscription.</p></section>
 <section className={styles.transition}><div><p className={styles.eyebrow}>ALREADY A MEMBER?</p><h2>Same identity. Your collection comes with you.</h2><p>Use the same email and sign-in method in the app. Your contributions, shelf, ratings, watches and granted access stay with that account.</p></div><div><h3>Android or unable to install?</h3><p>The iPhone app is the first native release. We are keeping an explicit web-access path for members who need it. No Android release date is being promised.</p><Link className={styles.secondary} href="/web-access">Keep using existing member tools ↗</Link><div className={styles.actions}><Link href="/settings">Manage billing or delete account</Link><Link href="/support">Contact support</Link></div></div></section>
 </main><footer className={styles.footer}><span>Bourbon Signal · A better signal for the hunt.</span><nav aria-label="Footer"><Link href="/legal/privacy">Privacy</Link><Link href="/legal/terms">Terms</Link><Link href="/legal/refunds">Refunds</Link><Link href="/support">Support</Link><Link href="/settings">Account deletion & billing</Link><Link href="/admin">Private admin</Link></nav><p>For adults of legal drinking age. Enjoy responsibly.</p></footer></div>;
}
