"""Prepare reviewed ImageGen masters; never generates or creatively edits images.

python scripts/prepare-label-free-art.py --jobs JOBS.json --masters DIR --batch 2
Requires Pillow. Existing exports whose master hash matches are reused.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
from PIL import Image


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def prepare(jobs_path, masters, batch, mobile):
    if not re.fullmatch(r"[1-9][0-9]*", str(batch)):
        raise ValueError("Batch must be a positive integer")
    jobs = json.loads(jobs_path.read_text(encoding="utf-8"))
    destination = mobile / "assets" / "bottles" / f"label-free-v{batch}"
    destination.mkdir(parents=True, exist_ok=True)
    previous_path = destination / "provenance.json"
    previous = json.loads(previous_path.read_text()) if previous_path.exists() else {"assets": []}
    previous_assets = {entry["file"]: entry for entry in previous["assets"]}
    catalog = json.loads((destination / "catalog.json").read_text())
    seed = {entry["id"]: entry for entry in json.loads((mobile / "src/cellar/bottle-catalog-seed.json").read_text())}
    shapes = [job["shape"] for job in jobs["jobs"]]
    if len(shapes) != len(set(shapes)) or set(shapes) != set(catalog["shapes"]):
        raise ValueError("Job shapes must exactly match the reviewed catalog shape allowlist")
    products = catalog["products"]
    if len({product["id"] for product in products}) != len(products):
        raise ValueError("Duplicate catalog product ID")
    for product in products:
        if product["shape"] not in shapes or seed.get(product["id"], {}).get("name") != product["name"]:
            raise ValueError(f"Unknown or stale catalog mapping: {product}")
    assets = []
    reused = 0
    for job in jobs["jobs"]:
        shape = job["shape"]
        if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", shape):
            raise ValueError("Invalid shape filename")
        filename = f"bare-{shape}.png"
        master = masters / job.get('masterFile', filename)
        target = destination / filename
        master_hash = sha(master)
        existing = previous_assets.get(filename)
        refinement = {key: job[key] for key in ('refinementPrompt', 'refinementReference') if key in job}
        if existing and existing["approvedMasterSha256"] == master_hash and target.exists() and sha(target) == existing["exportSha256"]:
            assets.append({**existing, **refinement})
            reused += 1
            continue
        with Image.open(master) as image:
            if image.mode != "RGBA" or image.getchannel("A").getextrema()[0] != 0:
                raise ValueError(f"True RGBA transparency required: {master}")
            image.thumbnail((540, 810), Image.Resampling.LANCZOS)
            image.save(target, optimize=True)
            assets.append({"shape": shape, "file": filename, "masterFile": master.name, "prompt": job["prompt"],
                           "reference": job["reference"], "referenceSha256": sha(Path(job["reference"])),
                           "approvedMasterSha256": master_hash, "exportSha256": sha(target),
                           "width": image.width, "height": image.height, "bytes": target.stat().st_size, **refinement})
    provenance = {"batch": batch, "method": jobs["method"], "styleReference": jobs["styleReference"],
                  "styleReferenceSha256": sha(Path(jobs["styleReference"])),
                  "export": "Proportional Lanczos downsampling to at most 540x810, then lossless RGBA PNG encoding. No geometry, color, label or background edits.",
                  "motion": "Existing native-driven expanded My Shelf motion; Reduce Motion and background pause retained.",
                  "assets": assets}
    previous_path.write_text(json.dumps(provenance, indent=2) + "\n", encoding="utf-8")
    registrations = []
    seen = set()
    for folder in sorted((mobile / "assets/bottles").glob("label-free-v*")):
        metadata = json.loads((folder / "provenance.json").read_text())
        for asset in metadata["assets"]:
            shape = asset.get("shape", asset["file"].removeprefix("bare-").removesuffix(".png"))
            if shape in seen:
                raise ValueError(f"Duplicate registered shape: {shape}")
            seen.add(shape)
            registrations.append(f"  '{shape}': require('../../assets/bottles/{folder.name}/{asset['file']}'),")
    module = "// Generated by scripts/prepare-label-free-art.py from reviewed provenance.\nexport const LABEL_FREE_ARTWORK = {\n" + "\n".join(registrations) + "\n} as const;\n"
    (mobile / "src/components/label-free-artwork-assets.ts").write_text(module, encoding="utf-8")
    print(json.dumps({"shapes": len(assets), "catalogEntries": len(products), "assetBytes": sum(asset["bytes"] for asset in assets), "exportsReused": reused, "registeredShapes": len(seen)}))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--jobs", type=Path, required=True)
    parser.add_argument("--masters", type=Path, required=True)
    parser.add_argument("--batch", type=int, required=True)
    args = parser.parse_args()
    prepare(args.jobs, args.masters, args.batch, Path(__file__).resolve().parents[1])
