"""Prepare reviewed ImageGen masters; never generates or creatively edits images.

python scripts/prepare-label-free-art.py --jobs JOBS.json --masters DIR --batch 2
Requires Pillow. Existing exports whose master hash matches are reused.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
from PIL import Image


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def register(mobile):
    """Generate both Metro assets and exact product mappings from all batches."""
    registrations, imports, batch_names, catalogs = [], [], [], []
    seen, ids, names = set(), set(), {}
    seed = {p['id']: p['name'] for p in json.loads((mobile / 'src/cellar/bottle-catalog-seed.json').read_text(encoding='utf-8'))}
    for folder in sorted((mobile / 'assets/bottles').glob('label-free-v*')):
        metadata = json.loads((folder / 'provenance.json').read_text(encoding='utf-8'))
        catalog = json.loads((folder / 'catalog.json').read_text(encoding='utf-8'))
        batch_name = f"batch{catalog['batch']}"
        imports.append(f"import {batch_name} from '../../assets/bottles/{folder.name}/catalog.json';")
        batch_names.append(batch_name)
        catalogs.append(catalog)
        local_shapes = set()
        for asset in metadata['assets']:
            shape = asset.get('shape', asset['file'].removeprefix('bare-').removesuffix('.png'))
            if shape in seen:
                raise ValueError(f'Duplicate registered shape: {shape}')
            seen.add(shape); local_shapes.add(shape)
            if sha(folder / asset['file']) != asset.get('exportSha256', asset.get('sha256')):
                raise ValueError(f"Export hash mismatch: {asset['file']}")
            registrations.append(f"  '{shape}': require('../../assets/bottles/{folder.name}/{asset['file']}'),")
        if set(catalog['shapes']) != local_shapes:
            raise ValueError(f'Catalog and exported shapes differ: {folder.name}')
    for catalog in catalogs:
        for product in catalog['products']:
            if product['id'] in ids or seed.get(product['id']) != product['name'] or product['shape'] not in seen:
                raise ValueError(f'Duplicate or stale product mapping: {product}')
            ids.add(product['id'])
            for name in [product['name'], *product.get('names', [])]:
                normalized = re.sub(r'[^a-z0-9]+', ' ', re.sub(r"['’.*]", '', name.lower())).strip()
                normalized = re.sub(r'\be h taylor\b', 'eh taylor', normalized)
                if normalized in names and names[normalized] != product['shape']:
                    raise ValueError(f'Conflicting artwork alias: {name}')
                names[normalized] = product['shape']
    module = '// Generated by scripts/prepare-label-free-art.py from reviewed provenance.\nexport const LABEL_FREE_ARTWORK = {\n' + '\n'.join(registrations) + '\n} as const;\n'
    (mobile / 'src/components/label-free-artwork-assets.ts').write_text(module, encoding='utf-8', newline='\n')
    catalog_module = '// Generated by scripts/prepare-label-free-art.py. Never edit batch imports by hand.\n' + '\n'.join(imports) + "\nimport type { LABEL_FREE_ARTWORK } from './label-free-artwork-assets';\n\nexport type ReviewedArtworkProduct = Readonly<{ id: string; name: string; shape: keyof typeof LABEL_FREE_ARTWORK; names?: readonly string[] }>;\nexport const LABEL_FREE_BATCHES = [" + ', '.join(batch_names) + "] as const;\nexport const FIRST_BATCH_PRODUCTS = batch1.products as readonly ReviewedArtworkProduct[];\nexport const LABEL_FREE_PRODUCTS = LABEL_FREE_BATCHES.flatMap(batch => batch.products) as readonly ReviewedArtworkProduct[];\n"
    (mobile / 'src/components/label-free-artwork-catalog.ts').write_text(catalog_module, encoding='utf-8', newline='\n')
    return {'registeredShapes': len(seen), 'totalCatalogEntries': len(ids)}


def prepare(jobs_path, masters, batch, mobile):
    if not re.fullmatch(r"[1-9][0-9]*", str(batch)):
        raise ValueError("Batch must be a positive integer")
    jobs = json.loads(jobs_path.read_text(encoding="utf-8"))
    destination = mobile / "assets" / "bottles" / f"label-free-v{batch}"
    destination.mkdir(parents=True, exist_ok=True)
    previous_path = destination / "provenance.json"
    previous = json.loads(previous_path.read_text(encoding='utf-8')) if previous_path.exists() else {"assets": []}
    previous_assets = {entry["file"]: entry for entry in previous["assets"]}
    catalog = json.loads((destination / "catalog.json").read_text(encoding='utf-8'))
    seed = {entry["id"]: entry for entry in json.loads((mobile / "src/cellar/bottle-catalog-seed.json").read_text(encoding='utf-8'))}
    shapes = [job["shape"] for job in jobs["jobs"]]
    if len(shapes) != len(set(shapes)) or set(shapes) != set(catalog["shapes"]):
        raise ValueError("Job shapes must exactly match the reviewed catalog shape allowlist")
    products = catalog["products"]
    if len({product["id"] for product in products}) != len(products):
        raise ValueError("Duplicate catalog product ID")
    reusable_shapes = set(shapes)
    for folder in (mobile / "assets/bottles").glob("label-free-v*"):
        if folder == destination:
            continue
        metadata = json.loads((folder / "provenance.json").read_text(encoding='utf-8'))
        for asset in metadata["assets"]:
            if sha(folder / asset["file"]) != asset.get("exportSha256", asset.get("sha256")):
                raise ValueError(f"Export hash mismatch: {asset['file']}")
            reusable_shapes.add(asset.get("shape", asset["file"].removeprefix("bare-").removesuffix(".png")))
    for product in products:
        if product["shape"] not in reusable_shapes or seed.get(product["id"], {}).get("name") != product["name"]:
            raise ValueError(f"Unknown or stale catalog mapping: {product}")
    assets = []
    reused = 0
    for job in jobs["jobs"]:
        shape = job["shape"]
        if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", shape):
            raise ValueError("Invalid shape filename")
        filename = f"bare-{shape}.png"
        master = masters / job.get('masterFile', filename)
        target = destination / filename
        master_hash = sha(master)
        existing = previous_assets.get(filename)
        refinement = {key: job[key] for key in ('refinementPrompt', 'refinementReference') if key in job}
        if existing and existing["approvedMasterSha256"] == master_hash and target.exists() and sha(target) == existing["exportSha256"]:
            assets.append({**existing, **refinement})
            reused += 1
            continue
        with Image.open(master) as image:
            if image.mode != "RGBA" or image.getchannel("A").getextrema()[0] != 0:
                raise ValueError(f"True RGBA transparency required: {master}")
            image.thumbnail((540, 810), Image.Resampling.LANCZOS)
            image.save(target, optimize=True)
            assets.append({"shape": shape, "file": filename, "masterFile": master.name, "prompt": job["prompt"],
                           "reference": job["reference"], "referenceSha256": sha(Path(job["reference"])),
                           "approvedMasterSha256": master_hash, "exportSha256": sha(target),
                           "width": image.width, "height": image.height, "bytes": target.stat().st_size, **refinement,
                           **{key: job[key] for key in ("referenceUrl", "sourceImageUrl") if key in job}})
    provenance = {"batch": batch, "method": jobs["method"], "styleReference": jobs["styleReference"],
                  "styleReferenceSha256": sha(Path(jobs["styleReference"])),
                  "export": "Proportional Lanczos downsampling to at most 540x810, then lossless RGBA PNG encoding. No geometry, color, label or background edits.",
                  "motion": "Existing native-driven expanded My Shelf motion; Reduce Motion and background pause retained.",
                  "assets": assets}
    previous_path.write_text(json.dumps(provenance, indent=2) + "\n", encoding="utf-8", newline="\n")
    registered = register(mobile)
    print(json.dumps({"shapes": len(assets), "catalogEntries": len(products), "assetBytes": sum(asset["bytes"] for asset in assets), "exportsReused": reused, **registered}))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--jobs", type=Path)
    parser.add_argument("--masters", type=Path)
    parser.add_argument("--batch", type=int)
    parser.add_argument("--register-only", action='store_true')
    args = parser.parse_args()
    mobile = Path(__file__).resolve().parents[1]
    if args.register_only:
        print(json.dumps(register(mobile)))
    else:
        if not args.jobs or not args.masters or not args.batch:
            parser.error('--jobs, --masters and --batch are required for preparation')
        prepare(args.jobs, args.masters, args.batch, mobile)
