import { useCallback, useEffect, useRef, useState } from 'react';
import { Image, Linking, ScrollView, Text, TextInput, View } from 'react-native';
import { useMobileApi } from '../../../src/hooks/useMobileApi';
import { ErrorState, LoadingState } from '../../../src/components/MemberScreen';
import { Action, workspaceStyles as s } from '../../../src/components/WorkspaceUI';
import { type OwnerCoverage, type OwnerMember, type OwnerSighting, type OwnerBottle, type OwnerReward, type ReviewRow, rewardNextStates } from '../../../../../shared/owner-workspace';
import { coverageStatusLabels, type CoverageStatus } from '../../../../../shared/coverage-requests';
type Section='Overview'|'Coverage'|'Members'|'Community'|'Rewards';
type Overview={coverage:number|null;community:number|null;bottles:number|null;rewards:number|null;founderShipping:number|null;checkedAt:string;unavailable:string[]};
export default function AdminScreen(){
  const api=useMobileApi();const [access,setAccess]=useState<boolean|null>(null);const [section,setSection]=useState<Section>('Overview');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(false);
  const [overview,setOverview]=useState<Overview|null>(null);const [coverage,setCoverage]=useState<OwnerCoverage|null>(null);const [members,setMembers]=useState<OwnerMember[]>([]);const [sightings,setSightings]=useState<OwnerSighting[]>([]);const [bottles,setBottles]=useState<OwnerBottle[]>([]);const [rewards,setRewards]=useState<OwnerReward[]>([]);const [query,setQuery]=useState('');const sequence=useRef(0);const [expanded,setExpanded]=useState<string|null>(null);
  function revoke(){setAccess(false);setOverview(null);setCoverage(null);setMembers([]);setSightings([]);setBottles([]);setRewards([]);}
  function accessError(e:unknown){if(e&&typeof e==='object'&&'status' in e&&(e.status===401||e.status===403))revoke();}
  useEffect(()=>{let live=true;setAccess(null);setOverview(null);setCoverage(null);setMembers([]);setSightings([]);setBottles([]);setRewards([]);api.getAdminAccess().then(a=>{if(live)setAccess(a.allowed);}).catch(()=>{if(live)setAccess(false);});return()=>{live=false;sequence.current++;};},[api]);
  const load=useCallback(async()=>{const ticket=++sequence.current;setLoading(true);setError('');try{
    if(section==='Overview'){const data=await api.getAdminData<Overview>('overview');if(ticket===sequence.current)setOverview(data);}
    if(section==='Coverage'){const data=await api.getAdminData<OwnerCoverage>('coverage');if(ticket===sequence.current)setCoverage(data);}
    if(section==='Members'){const data=await api.getAdminData<{members:OwnerMember[]}>('members',`?q=${encodeURIComponent(query)}`);if(ticket===sequence.current)setMembers(data.members);}
    if(section==='Community'){const [a,b]=await Promise.all([api.getAdminData<{sightings:OwnerSighting[]}>('sightings'),api.getAdminData<{contributions:OwnerBottle[]}>('bottle-contributions')]);if(ticket===sequence.current){setSightings(a.sightings);setBottles(b.contributions.filter(x=>x.status==='new'||x.status==='needs_human'));}}
    if(section==='Rewards'){const data=await api.getAdminData<{queue:OwnerReward[]}>('signal-points');if(ticket===sequence.current)setRewards(data.queue);}
  }catch(e){accessError(e);if(ticket===sequence.current)setError(e instanceof Error?e.message:'Admin data could not load.');}finally{if(ticket===sequence.current)setLoading(false);}},[api,section,query]);
  useEffect(()=>{if(access && section!=='Members')void load();},[access,section,api]);
  async function save(part:'coverage'|'sightings'|'bottle-contributions'|'signal-points',body:Record<string,unknown>){if(busy)return;setBusy(true);setError('');try{await api.saveAdminReview(part,body);await load();}catch(e){accessError(e);setError(e instanceof Error?e.message:'Review could not save.');}finally{setBusy(false);}}
  const openWeb=(path='')=>void Linking.openURL(`https://www.bourbonsignal.com/admin${path}`).catch(()=>setError('The web workspace could not open.'));
  if(access===null)return <LoadingState label="Checking admin access…"/>;
  if(!access)return <View style={s.content}><Text style={s.heading}>Admin access unavailable</Text><Text style={s.copy}>This workspace is restricted to the owner account.</Text></View>;
  const grouped=new Map<string,ReviewRow[]>();for(const row of coverage?.requests||[]){const key=row.canonicalTargetKey||row.id;grouped.set(key,[...(grouped.get(key)||[]),row]);}
  return <ScrollView style={s.screen} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Text style={s.title}>Your admin workspace</Text><View style={s.wrap}>{(['Overview','Coverage','Members','Community','Rewards'] as Section[]).map(tab=><Action key={tab} label={tab} selected={section===tab} onPress={()=>setSection(tab)}/>)}</View>
    {error?<ErrorState message={error} onRetry={()=>void load()}/>:null}{loading?<LoadingState label="Refreshing workspace…"/>:null}
    {section==='Overview'?<><Text style={s.heading}>Needs attention</Text>{overview?Object.entries({Coverage:overview.coverage,Community:overview.community,'Bottle submissions':overview.bottles,Rewards:overview.rewards,'Founder shipments':overview.founderShipping}).map(([label,count])=><Action key={label} label={`${label} · ${count===null?'Unavailable':count}`} onPress={()=>label==='Founder shipments'?openWeb('/control-room#founder-glasses'):setSection(label==='Bottle submissions'?'Community':label as Section)}/>):null}{overview?.unavailable.length?<Text style={s.copy}>Some queues couldn’t refresh. Their counts are unavailable, not zero.</Text>:null}<Action label="Pricing reviews →" onPress={()=>openWeb('?section=Pricing')}/><Action label="Service health →" onPress={()=>openWeb('/operations')}/><Action label="Open web workspace →" onPress={()=>openWeb()}/></>:null}
    {section==='Coverage'?<><Text style={s.copy}>Requested keeps investigation queued. Under review pauses automation for your review. Member updates appear in their request history.</Text>{[...grouped.entries()].sort((a,b)=>Number(b[1].some(r=>r.review?.priority==='high'))-Number(a[1].some(r=>r.review?.priority==='high'))||b[1].length-a[1].length).map(([key,rows])=><View key={key} style={s.card}><Text style={s.heading}>{rows[0].storeName||rows[0].areaLabel}, {rows[0].stateCode}</Text><Text style={s.copy}>{new Set(rows.map(r=>r.userId)).size} members requested this location</Text>{<Action label={expanded===key?"Hide reviews ↑":"Review requests →"} onPress={()=>setExpanded(expanded===key?null:key)}/>} {expanded===key?rows.map(row=><CoverageReview key={row.id} row={row} busy={busy} onSave={body=>void save('coverage',body)}/>):null}</View>)}{coverage?.requests.length===0?<Text style={s.copy}>No coverage requests to review.</Text>:null}</>:null}
    {section==='Members'?<><TextInput accessibilityLabel="Search members" placeholder="Name, email or member number" placeholderTextColor="#a99e8e" value={query} onChangeText={setQuery} style={s.input}/><Action label="Search" disabled={loading||!query.trim()} onPress={()=>void load()}/>{members.map(m=><View key={m.id} style={s.card}><Text style={s.heading}>{m.name||m.email}</Text><Text selectable style={s.copy}>{m.email}</Text><Text style={s.success}>{m.numberLabel} #{m.number || 'Unassigned'} · {m.tier} · {m.status}</Text></View>)}{query&&!loading&&members.length===0?<Text style={s.copy}>Search to find matching members.</Text>:null}</>:null}
    {section==='Community'?<><Text style={s.heading}>Sightings needing review</Text>{sightings.map(r=><SightingReview key={r.id} row={r} busy={busy} onSave={body=>void save('sightings',body)} onOpenWeb={()=>openWeb('/sightings')}/>)}<Text style={s.heading}>Bottle submissions</Text>{bottles.map(r=><View key={r.id} style={s.card}><Text style={s.heading}>{r.rawName||r.bottleName||r.name||r.id}</Text><Text style={s.copy}>{r.notes}</Text>{r.candidateBottleId?<Action label={`Use match: ${r.candidateBottleName}`} disabled={busy} onPress={()=>void save('bottle-contributions',{id:r.id,action:'use_match',candidateBottleId:r.candidateBottleId,candidateBottleName:r.candidateBottleName})}/>:null}<Action label="Dismiss submission" disabled={busy} onPress={()=>void save('bottle-contributions',{id:r.id,action:'dismiss'})}/><Action label="Full bottle review →" onPress={()=>openWeb('/bottle-queue')}/></View>)}{!sightings.length&&!bottles.length?<Text style={s.copy}>Nothing waiting for review.</Text>:null}</>:null}
    {section==='Rewards'?<>{rewards.map(r=><RewardReview key={r.id} row={r} busy={busy} onSave={body=>void save('signal-points',body)}/>)}{!rewards.length?<Text style={s.copy}>No rewards waiting for fulfillment.</Text>:null}<Action label="Founder glass shipments →" onPress={()=>openWeb('/control-room#founder-glasses')}/></>:null}
    <Action label="Refresh" disabled={loading||busy} onPress={()=>void load()}/>
  </ScrollView>;
}
function CoverageReview({row,busy,onSave}:{row:ReviewRow;busy:boolean;onSave:(body:Record<string,unknown>)=>void}){const [note,setNote]=useState(row.review?.internal_note||'');const [update,setUpdate]=useState(row.review?.member_update||'');const [priority,setPriority]=useState(row.review?.priority||'normal');const [status,setStatus]=useState(row.status);return <View style={{gap:10}}><Text style={s.success}>{coverageStatusLabels[row.status as CoverageStatus]} · {row.updatedAt?.slice(0,10)}</Text><Text style={s.label}>Private note</Text><TextInput accessibilityLabel="Private coverage note" style={s.input} value={note} onChangeText={setNote} maxLength={1000} multiline/><Text style={s.label}>Member update (shown in their request history)</Text><TextInput accessibilityLabel="Member coverage update" style={s.input} value={update} onChangeText={setUpdate} maxLength={500} multiline/><View style={s.wrap}>{(['requested','on_radar','closed'] as const).map(st=><Action key={st} label={coverageStatusLabels[st]} selected={status===st} onPress={()=>setStatus(st)}/>)}</View><Action label={priority==='high'?'High priority ✓':'Set high priority'} onPress={()=>setPriority(priority==='high'?'normal':'high')}/><Action label="Save review" disabled={busy||status==='improved'} onPress={()=>onSave({id:row.id,status,internalNote:note,memberUpdate:update,priority})}/></View>;}
function RewardReview({row,busy,onSave}:{row:OwnerReward;busy:boolean;onSave:(body:Record<string,unknown>)=>void}){const [carrier,setCarrier]=useState(row.carrier||'');const [tracking,setTracking]=useState(row.trackingNumber||'');return <View style={s.card}><Text style={s.heading}>{row.itemKey.replaceAll('_',' ')}</Text><Text style={s.copy}>{row.accountEmail} · {row.pointsSpent} points · {row.status.replaceAll('_',' ')}</Text>{row.shippingAddress?<Text selectable style={s.copy}>{Object.values(row.shippingAddress).filter(Boolean).join(', ')}</Text>:null}{row.status==='packed'?<><TextInput accessibilityLabel="Shipping carrier" style={s.input} placeholder="Carrier" placeholderTextColor="#a99e8e" value={carrier} onChangeText={setCarrier}/><TextInput accessibilityLabel="Tracking number" style={s.input} placeholder="Tracking number" placeholderTextColor="#a99e8e" value={tracking} onChangeText={setTracking}/></>:null}{rewardNextStates(row).map(status=><Action key={status} label={`Mark ${status.replaceAll('_',' ')}`} disabled={busy||(status==='shipped'&&(!carrier.trim()||!tracking.trim()))} onPress={()=>onSave({redemptionId:row.id,status,carrier,trackingNumber:tracking})}/>)}</View>;}

function SightingReview({row,busy,onSave,onOpenWeb}:{row:OwnerSighting;busy:boolean;onSave:(body:Record<string,unknown>)=>void;onOpenWeb:()=>void}) {
 const [reason,setReason]=useState('');const [loadedPhoto,setLoadedPhoto]=useState('');const [photoFailed,setPhotoFailed]=useState(false);const proof=row.rewardState?.photoProof;
 const act=(action:string)=>onSave({reporterUserId:row.reporterUserId,sightingId:row.id,action,reason});
 return <View style={s.card}><Text style={s.heading}>{row.bottleName}</Text><Text style={s.copy}>{row.reporterName} · {row.storeName}</Text><Text style={s.copy}>{row.reviewReasons.join(', ')}</Text>
  {proof?.url?.startsWith('https://')&&!photoFailed?<Image accessibilityLabel="Sighting photo evidence" source={{uri:proof.url}} style={{width:'100%',height:220,borderRadius:12}} resizeMode="contain" onLoad={()=>setLoadedPhoto(proof.url)} onError={()=>setPhotoFailed(true)}/>:null}
  {photoFailed?<Text style={s.copy}>Photo could not load. Open the full review before approving it.</Text>:null}
  <Text style={s.label}>Review note</Text><TextInput accessibilityLabel="Sighting review note" value={reason} onChangeText={setReason} maxLength={180} style={s.input} multiline/>
  {proof?.status==='pending'?<><Action label="Approve with public photo" disabled={busy||photoFailed||loadedPhoto!==proof.url} onPress={()=>act('verify_public')}/><Action label="Approve, keep photo private" disabled={busy||photoFailed||loadedPhoto!==proof.url} onPress={()=>act('verify_private')}/><Action label="Reject photo" disabled={busy||reason.trim().length<3} onPress={()=>act('reject_photo')}/></>:null}
  <Action label="Resolve bottle and store review" disabled={busy} onPress={()=>act('resolve_manual_review')}/><Action label="Reject sighting" disabled={busy||reason.trim().length<3} onPress={()=>act('reject_sighting')}/><Action label="Full evidence and contributor history →" onPress={onOpenWeb}/>
 </View>;
}
