export const LEGAL_UPDATED = 'October 5, 2026';
export const PRIVACY_INTRO = 'This policy explains how Todd Digital Ventures LLC uses information to run Bourbon Signal on the website and in the app.';
export const TERMS_INTRO = 'These terms apply to Bourbon Signal, operated by Todd Digital Ventures LLC. The service includes bottle availability information, community posts, collections, alerts, memberships and rewards.';
export const PRIVACY_SECTIONS = [
 ['Account and membership', ['We collect your account email, authentication identifiers, display name, member number and account settings. We receive subscription status, purchase identifiers and billing records from providers such as Apple, RevenueCat and Stripe. We do not store full payment-card numbers on our servers.']],
 ['Collections, preferences and requests', ['We store bottles, quantities, ratings, tasting preferences and notes you save, along with selected locations, watched bottles and notification preferences. We store Community abuse reports and member blocks to investigate concerns and keep blocked posts and future Community alerts out of your account. We also store coverage requests, reward redemptions, referrals and information needed to fulfill rewards, including shipping details when you provide them.']],
 ['What other members can see', ['Community posts may show your display name, Founder or Member number, bottle and store details, and photos you choose to attach. Your account email, private collection notes and reward shipping address are not part of your public member tag.']],
 ['How we use your information', ['We use information to provide feeds and alerts, manage memberships and rewards, personalize collection features, investigate coverage requests, provide support, improve the service and prevent abuse. We may use aggregated or de-identified information to understand demand and coverage quality.']],
 ['Device information and notifications', ['We process device and browser details, logs, errors, performance information and approximate IP-based location. If you enable phone notifications, we register a device push token and use your preferences to deliver alerts. You can change notification settings in Radar and your device settings. Bottle alerts are not delivered by SMS or email. Account, billing and security email may still be sent, and marketing email includes an unsubscribe option.']],
 ['Service providers and sharing', ['Providers help us host the service, authenticate accounts, store data, verify purchases, process payments, deliver notifications and email, and handle support. These include Vercel, Clerk, Apple, RevenueCat, Stripe and our database and email providers. We may disclose information at your direction, to fulfill a transaction, comply with law, protect rights and safety, or as part of a business transfer. We do not sell customer lists for money.']],
 ['Website storage', ['The website and its providers use cookies or similar storage for sign-in, security, preferences and service operation. Your browser controls may affect these features.']],
 ['Your choices and account deletion', ['You can edit your profile and preferences in Account. To delete your account, open Account → Delete account in the app. Deletion and subscription cancellation are separate actions; manage an Apple subscription through the App Store. Contact support@bourbonsignal.com for help or privacy questions.']],
 ['Retention and security', ['We retain information for service operation, accounting, disputes, fraud prevention and legal requirements. Deletion removes active product access and starts the cleanup of associated information; limited records may remain where required. Historical consent or delivery records from retired features may be retained for those purposes. We use technical and organizational safeguards, but no online service can guarantee perfect security.']],
 ['Age and policy changes', ['Bourbon Signal is for adults age 21 and older. We do not knowingly collect information from children or people under the legal drinking age. We update this policy as the service changes and communicate material changes where required.']],
] as const;
export const TERMS_SECTIONS = [
 ['What the service does', ['Bourbon Signal helps you monitor bottle availability using public sources, retailers and community sightings. We do not sell, ship, broker, reserve or deliver alcoholic beverages. We are not an alcohol retailer or marketplace.']],
 ['Who can use it', ['You must be at least 21 years old and comply with applicable alcohol laws and retailer policies. Keep your account information accurate and protect your sign-in credentials.']],
 ['Availability information and alerts', ['Inventory and shipment information can be delayed, incomplete or incorrect. Bottles may sell out before you arrive. Check availability, price and purchase limits with the retailer before traveling. Alerts may be delayed or not delivered because of source timing, device settings or service interruptions. An alert never reserves a bottle.']],
 ['Collection estimates', ['Collection values are approximate references, not appraisals or guaranteed sale proceeds. MSRP refers to the published manufacturer price for the stated release. Secondary estimates depend on dated market evidence and bottle condition. Missing prices are excluded and coverage counts identify which bottles contribute. Open bottles are excluded from secondary estimates. Size, vintage, batch and store picks can change value; taxes and selling fees are excluded unless a reference explicitly says otherwise.']],
 ['Memberships and billing', ['Paid subscriptions renew automatically unless you cancel before renewal. Apple handles purchases made through the iOS app; manage those subscriptions in the App Store. Other purchases are managed through their payment platform. Cancellation stops future renewal and generally leaves access until the paid period ends. It does not automatically refund previous charges. Deleting an account does not cancel an Apple subscription.']],
 ['Refunds and Founder access', ['Subscriptions are generally non-refundable after a billing period begins, except where required by law, the payment platform’s rules or our discretion. Founder purchases provide lifetime access under the original Founder offer and are non-refundable except where applicable law or payment-platform rules require otherwise. We communicate material membership changes before they affect active subscribers where required.']],
 ['Community and rewards', ['Only post information and photos you have the right to share. Do not post false sightings, private personal information, harassment or unlawful content. Use Report this post or Block this member on a Community post, or contact support@bourbonsignal.com. Blocked members can be managed from Account in the app or the Community safety page on the website. We may review or remove posts and restrict accounts that abuse the service. Photos appear publicly only after approval for public display. Signal Points and rewards follow the eligibility, availability and redemption rules shown in the app; they are not cash or transferable money. Coverage requests help prioritize investigation and do not promise a delivery date.']],
 ['Acceptable use and ownership', ['Do not disrupt the service, abuse source systems, scrape at unreasonable volume, resell our data or commercially republish it without written permission. Bourbon Signal’s software, design and original content belong to Todd Digital Ventures LLC or its licensors. Product names, retailer names and trademarks belong to their owners. Naming a source or brand does not imply endorsement or partnership.']],
 ['Service limits and liability', ['The service is provided as-is and as-available. To the fullest extent permitted by law, we disclaim warranties of accuracy, availability, merchantability, fitness for a particular purpose and non-infringement. Todd Digital Ventures LLC and Bourbon Signal are not liable for indirect, incidental, consequential, punitive or lost-profit damages, or decisions based on signals, alerts, estimates or source data, to the fullest extent permitted by law.']],
 ['Changes and questions', ['We may update these terms as the service evolves. Continued use after changes means you accept the updated terms, subject to any notice or consent required by law. For questions, email support@bourbonsignal.com.']],
] as const;
