import assert from 'node:assert/strict';
import {directoryPage,adminMember} from '../src/lib/admin-member-directory';
import {expandCorrectedWatchNames} from '../src/lib/admin-watch-aliases';
const now=new Date('2026-10-06T12:00:00Z');
const users=Array.from({length:83},(_,i)=>({id:`u${String(i).padStart(3,'0')}`,firstName:`Member ${i}`,emailAddresses:[{emailAddress:`member${i}@example.test`}],createdAt:i+1,lastSignInAt:83-i,publicMetadata:{memberNumber:i+1,tier:i%2?'standard':'free',membershipStatus:i%2?'active':'free'},privateMetadata:i%2?{stripeSubscriptionId:`s${i}`}:{}}));
const page=(query='')=>directoryPage(users,new URLSearchParams(query),now);
assert.equal(page().members.length,40);assert.equal(page().total,83);assert.equal(page().nextOffset,40);
assert.equal(page('offset=40').members.length,40);assert.equal(page('offset=80').members.length,3);assert.equal(page('offset=80').nextOffset,null);
assert.equal(new Set([...page().members,...page('offset=40').members,...page('offset=80').members].map(m=>m.id)).size,83);
assert.equal(page('filter=paid').total,41);assert.equal(page('filter=free').total,42);
assert.equal(page('q=member17%40').members[0].id,'u017');assert.equal(page('sort=activity').members[0].id,'u000');assert.equal(page('sort=joined_asc').members[0].id,'u000');
assert.throws(()=>page('offset=-1'));assert.throws(()=>page('filter=owner'));assert.throws(()=>page('sort=secret'));
const gifted=adminMember({id:'gift',publicMetadata:{tier:'barrel',plan:'gift_barrel_annual',membershipStatus:'active',giftOrderId:'gift',giftAccessExpiresAt:'2027-01-01'}},now);
assert.equal(gifted.tier,'barrel');assert.deepEqual(gifted.accessSources,['gifted']);
const earned=adminMember({id:'earned',publicMetadata:{tier:'free',rewardMembershipRedemptionId:'r',rewardMembershipExpiresAt:'2026-11-01'},unsafeMetadata:{tier:'bottled-in-bond',membershipStatus:'lifetime'}},now);
assert.equal(earned.tier,'standard');assert.deepEqual(earned.accessSources,['earned']);
assert.equal(adminMember({id:'expired',publicMetadata:{tier:'standard',plan:'gift_standard_annual',membershipStatus:'active',giftOrderId:'g',giftAccessExpiresAt:'2020-01-01'}},now).tier,'free');
const records=[{patch:{canonicalName:'Corrected exact batch',aliases:['Original misspelling','Corrected exact batch']},redirect_id:null}];
assert.deepEqual(expandCorrectedWatchNames(['Original misspelling'],records,s=>s.toLowerCase()),['Original misspelling','Corrected exact batch']);
assert.deepEqual(expandCorrectedWatchNames(['Different batch'],records,s=>s.toLowerCase()),['Different batch']);
console.log('Directory paging, access/billing distinction, expired gifts, earned access, unsafe metadata and exact watch alias continuity passed.');
const apple=adminMember({id:'apple',publicMetadata:{appleMembershipTier:'barrel',appleMembershipPlan:'barrel_monthly',appleMembershipStatus:'trialing',appleMembershipExpiresAt:'2026-11-01'}},now);
assert.equal(apple.tier,'barrel');assert.deepEqual(apple.accessSources,['trial']);
const google=adminMember({id:'google',publicMetadata:{googleMembershipTier:'standard',googleMembershipPlan:'standard_monthly',googleMembershipStatus:'active',googleMembershipExpiresAt:'2026-11-01'}},now);
assert.equal(google.tier,'standard');assert.equal(google.billingProvider,'google');assert.equal(google.billingStatus,'active');assert.deepEqual(google.accessSources,['paid']);
