import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { normalizeCheckoutSource } from "../src/lib/growth-events.ts";

assert.equal(normalizeCheckoutSource("drop_feed"), "drop_feed");
assert.equal(normalizeCheckoutSource("release-radar"), "unknown");
assert.equal(normalizeCheckoutSource("https://evil.example/?email=x@example.com"), "unknown");
const checkoutRoute = readFileSync("src/app/api/checkout/route.ts", "utf8");
const syncRoute = readFileSync("src/app/api/checkout/sync/route.ts", "utf8");
const pricingPage = readFileSync("src/app/pricing/PricingPageClient.tsx", "utf8");
assert.match(checkoutRoute, /source:\s*["']bourbon_signal_launch["']/);
assert.match(checkoutRoute, /attributionSurface:\s*source/);
assert.match(syncRoute, /metadata\?\.source\s*!==\s*["']bourbon_signal_launch["']/);
assert.match(checkoutRoute, /checkout_started/);
assert.match(checkoutRoute, /cancel_url:\s*`\$\{origin\}\/pricing\?canceled=\$\{plan\.id\}/, "Stripe cancellation must return with the distinct canceled plan parameter");
assert.doesNotMatch(checkoutRoute, /cancel_url:[^\n]*\?checkout=/, "canceling Stripe must not use the auto-continuation parameter");
assert.match(pricingPage, /Checkout canceled\. You were not charged\./);
assert.match(pricingPage, /"Resume checkout"/);
assert.match(pricingPage, />Choose another plan</);
assert.match(pricingPage, /"Continue with Free"/);
assert.match(pricingPage, /"Continue with current plan"/);
assert.match(pricingPage, /Your current membership is still active/);
assert.match(pricingPage, /onClick=\{\(\) => startCheckout\(canceledPlan,/);
assert.match(pricingPage, /isLoaded && canceledPlan/, "cancellation recovery must wait for auth hydration");
assert.match(pricingPage, /checkoutInFlight\.current[\s\S]*disabled=\{pendingPlan === canceledPlan\}/, "checkout recovery must prevent concurrent Stripe session creation");
assert.doesNotMatch(pricingPage, /useEffect\([\s\S]{0,500}canceledPlan[\s\S]{0,500}startCheckout/, "a canceled plan may resume only from an explicit click");
console.log("Checkout attribution contract passed.");
