import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const feed = readFileSync(new URL("../src/components/sections/DropFeed.tsx", import.meta.url), "utf8");
const composer = readFileSync(new URL("../src/components/signals/InlineSignalComposer.tsx", import.meta.url), "utf8");
const hero = readFileSync(new URL("../src/components/sections/HeroSection.tsx", import.meta.url), "utf8");
const packageSource = readFileSync(new URL("../package.json", import.meta.url), "utf8");
assert.match(packageSource, /"test:main-feed-composer"/);
assert.match(packageSource, /"verify:ci"[^\n]+test:main-feed-composer/);

assert.match(feed, /InlineSignalComposer/);
assert.match(feed, /<InlineSignalComposer/);
assert.match(feed, /addSighting=\{addSighting\}/);
assert.match(feed, />\s*Signals\s*</);
assert.doesNotMatch(feed, />\s*Signal Feed\s*</);
assert.match(feed, /Live bourbon activity from members, retailers, and trusted sources\./);
assert.match(feed, /All signals/);
assert.doesNotMatch(feed, /All drops/);
assert.match(feed, /dropfeed-mobile-filter-toggle/);
assert.match(feed, /dropfeed-active-filter-chips/);
assert.match(feed, /const stateDropdownValue = urlStateFilter \|\|/);
assert.match(feed, /mobileFiltersOpen/);
assert.match(feed, /SignalSummary/);
assert.doesNotMatch(feed, /SignalTicker/);
assert.doesNotMatch(feed, /matching signals\$\{data\.lastUpdated/);
assert.match(composer, /Post a Signal/);
assert.match(composer, /addSighting\(sighting\)/);
assert.match(composer, /makeSightingId/);
assert.match(composer, /needsBottleReview/);
assert.match(composer, /needsStoreReview/);
assert.match(composer, /seen_in_store/);
assert.match(composer, /online_social/);
assert.match(composer, /Use an exact store|Select exact store/);
assert.match(composer, /buildSightingStoreSearchIndex/);
assert.match(composer, /searchSightingStoreIndex/);
assert.match(composer, /manualStateEdited/);
assert.match(composer, /useEffect\([^]*defaultState/);
assert.match(composer, /Share a bottle you found\./);
assert.match(composer, /ArrowRight/);
assert.match(composer, /Close/);
assert.doesNotMatch(composer, /ChevronDown/);
assert.match(composer, /signIn/);
assert.doesNotMatch(composer, /scout/i);
assert.match(hero, /home-hero/);
assert.match(hero, /@media\(max-width:767px\)/);
assert.match(hero, /height:78svh/);

console.log("Main Signal Feed composer contract passed.");
