import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const feed = readFileSync(new URL("../src/components/sections/DropFeed.tsx", import.meta.url), "utf8");
const composer = readFileSync(new URL("../src/components/signals/InlineSignalComposer.tsx", import.meta.url), "utf8");
const hero = readFileSync(new URL("../src/components/sections/HeroSection.tsx", import.meta.url), "utf8");
const packageSource = readFileSync(new URL("../package.json", import.meta.url), "utf8");
assert.match(packageSource, /"test:main-feed-composer"/);
assert.match(packageSource, /"verify:ci"[^\n]+test:main-feed-composer/);

assert.match(feed, /InlineSignalComposer/);
assert.match(feed, /<InlineSignalComposer/);
assert.match(feed, /addSighting=\{addSighting\}/);
assert.match(feed, />\s*Signals\s*</);
assert.doesNotMatch(feed, />\s*Signal Feed\s*</);
assert.match(feed, /Live bourbon activity from members, retailers, and trusted sources\./);
assert.match(feed, /All signals/);
assert.doesNotMatch(feed, /All drops/);
assert.doesNotMatch(feed, /dropfeed-mobile-filter-toggle/);
assert.doesNotMatch(feed, /dropfeed-active-filter-chips/);
assert.match(feed, /const stateDropdownValue = urlStateFilter \|\|/);
assert.doesNotMatch(feed, /mobileFiltersOpen/);
assert.match(feed, /SignalTicker/);
assert.doesNotMatch(feed, /SignalSummary/);
assert.match(feed, /signal-ticker-track/);
assert.doesNotMatch(feed, /setTickerPaused/);
assert.doesNotMatch(feed, /aria-pressed=\{tickerPaused\}/);
assert.doesNotMatch(feed, /signal-ticker-toggle/);
assert.doesNotMatch(feed, /border-block:/);
assert.doesNotMatch(feed, /<SignalTicker[^]*borderBottom[^]*<InlineSignalComposer/);
assert.match(feed, /\.signal-ticker-track\.reduced[^}]*flex-wrap:\s*wrap/s);
assert.match(feed, /value < 0/);
assert.match(feed, /Observations processed/);
assert.match(feed, /Current observations/);
assert.doesNotMatch(feed, /Total signals detected/);
assert.doesNotMatch(feed, /Live signals/);
assert.match(feed, /Stores monitored/);
assert.match(feed, /Member Count/);
assert.match(feed, /Last refreshed/);
assert.match(feed, /currentObservations=\{data\?\.total\}/);
assert.match(feed, /Showing \$\{displayedGrouped\.length\} \$\{hasActiveFeedFilters \? "filtered " : ""\}signal cards/);
assert.match(feed, /tabIndex=\{0\}/);
assert.match(feed, /\.signal-ticker:focus \.signal-ticker-track/);
assert.match(feed, /canUseStateFilter \|\| canUseBottleSearch \|\| canUseDropFeedFilters/);
assert.doesNotMatch(feed, /matching signals\$\{data\.lastUpdated/);
assert.match(composer, /Post a Signal/);
assert.match(composer, /addSighting\(sighting\)/);
assert.match(composer, /makeSightingId/);
assert.match(composer, /needsBottleReview/);
assert.match(composer, /needsStoreReview/);
assert.match(composer, /seen_in_store/);
assert.match(composer, /online_social/);
assert.match(composer, /Use an exact store|Select exact store/);
assert.match(composer, /buildSightingStoreSearchIndex/);
assert.match(composer, /searchSightingStoreIndex/);
assert.match(composer, /manualStateEdited/);
assert.match(composer, /useEffect\([^]*defaultState/);
assert.match(composer, /BottleSignalIcon/);
assert.match(composer, /What bottle did you find\?/);
assert.match(composer, /Search store, city, ZIP, or street/);
assert.match(composer, /inline-signal-starter/);
assert.match(composer, /Required to post/);
assert.match(composer, /Optional details/);
assert.doesNotMatch(composer, /\bPlus\b/);
assert.doesNotMatch(composer, /ArrowRight/);
assert.doesNotMatch(composer, /<span>Open<\/span>/);
assert.match(composer, /aria-label="Close composer"/);
assert.match(composer, /onFocus=\{expandPost\}/);
assert.doesNotMatch(composer, /onFocus=\{beginPost\}/);
assert.doesNotMatch(composer, /ChevronDown/);
assert.match(composer, /signIn/);
assert.doesNotMatch(composer, /scout/i);
assert.match(hero, /home-hero/);
assert.match(hero, /@media\(max-width:767px\)/);
assert.match(hero, /height:78svh/);
assert.match(hero, /home-hero-features/);
assert.match(hero, /home-hero-features\{display:none/);
assert.match(hero, /white-space:normal/);

console.log("Main Signal Feed composer contract passed.");
